- package.json
- packages/buble/CHANGELOG.md
- packages/buble/README.md
- packages/buble/index.d.ts
- packages/buble/package.json
- packages/buble/rollup.config.js
- packages/buble/src/index.js
- packages/buble/test/samples/basic/main.js
- packages/buble/test/test.js
- packages/buble/test/types.ts
- pnpm-lock.yaml
- Rollup Plugin Name: `@rollup/plugin-buble
This PR migrates `rollup-plugin-buble` to this monorepo.
> Migrate rollup-plugin-buble

- packages/virtual/README.md
> fix: virtual name in README (#62)

- packages/html/README.md
_maintainer edit_ Fixes a `<br>` tag in the html plugin README
> docs(html): fix <br> tag

- README.md
Prior to this change, the `@rollup/plugin-typescript` package was not linked in the README for the overarching repository.
> add typescript to readme

- packages/alias/package.json
> chore: better homepage link for alias

- packages/replace/package.json
> chore: fix homepage link in package.json

- packages/buble/README.md
- packages/commonjs/README.md
- packages/inject/README.md
- packages/replace/README.md
- packages/typescript/README.md
Consistently use <br> in markdown for line breaks in `## Options`.
> docs: <br> line breaks

- packages/typescript/README.md
- packages/typescript/package.json
Sucrase has the same behaviour as the `ts.transpileModule` API we previously used, and is also 20x faster. Let's direct users to this plugin if they need the old behaviour.
Also adding myself to the contributors list :)
> core(typescript): Add note about old behaviour

- packages/pluginutils/src/createFilter.ts
- packages/pluginutils/src/dataToEsm.ts
- packages/pluginutils/src/utils/ensureArray.ts
- packages/pluginutils/types/index.d.ts
Improve IDE experience by adding comments in the types. Update `FilterPattern` to use `ReadonlyArray` so that consumers can use immutable arrays with plugins.
> chore(pluginutils): Use readonly arrays, add TSDoc

- packages/alias/package.json
- packages/alias/rollup.config.js
- packages/alias/src/index.ts
- packages/alias/tsconfig.json
- packages/alias/types/index.d.ts
- pnpm-lock.yaml
Rewrite the alias plugin in Typescript.
> feat(alias): Move to Typescript

- packages/beep/package.json
- packages/beep/types/index.d.ts
Adds types to beep. This plugin is pretty simple so there's no need for Typescript.
> feat(beep): Add types

- packages/auto-install/package.json
- packages/auto-install/rollup.config.js
- packages/auto-install/src/index.ts
- packages/auto-install/tsconfig.json
- packages/auto-install/types/index.d.ts
- pnpm-lock.yaml
Rewrite the auto-install plugin in Typescript.
> feat(auto-install): Move to Typescript

- packages/buble/README.md
- packages/buble/package.json
- packages/buble/rollup.config.js
- packages/buble/src/index.ts
- packages/buble/tsconfig.json
- pnpm-lock.yaml
Moves buble plugin to Typescript.
> chore(buble): Move to Typescript

- .github/PULL_REQUEST_TEMPLATE.md
Adding a note to the PR template since I wasn't aware of this convention.
> chore: add note on breaking commit titles

- packages/node-resolve/README.md
> docs(node-resolve): Correct the resolver package name

- packages/typescript/src/options/interfaces.ts
- packages/typescript/src/options/normalize.ts
- packages/typescript/src/options/plugin.ts
- packages/typescript/src/options/tsconfig.ts
- packages/typescript/types/index.d.ts
Used internal types to improve the interface
Tweaks the options interface using unions.
> feat(typescript): Refine options interface

- packages/commonjs/README.md
Correcting misspelled word: "depdenencies" to "dependencies"
> Correcting misspelled word

- packages/data-uri/test/test.js
- packages/typescript/src/index.ts
rollup/plugins#322
Just check if program already exists before creating a new one.
> fix(typescript): fix a memory leak (#322)

- packages/typescript/README.md
This PR updates a link to @rollup/plugin-babel in the @rollup/plugin-typescript README
> Update link to @rollup/plugin-babel in README.md

- packages/typescript/package.json
List any relevant issue numbers: #452
Fixes the peer dependency version. This isn't a breaking change because we already required this version, and just didn't specify it properly in the package.json.
> fix(typescript): Fix peer dep version

- packages/babel/README.md
> Remove unused import in "Usage" example

- packages/strip/README.md
#450 
Adds references to `include` and `exclude` options.
> chore: update README

- packages/node-resolve/README.md
just ran into what's described in #412
this updates the readme to reflect the latest version of the module
> add .nodeResolve change to the readme

- packages/replace/README.md
Replacing process.env.NODE_ENV is the most popular case for this plugin. We should have it in readme.
See here https://github.com/ai/nanoid/issues/236
> docs(replace): describe process.env.NODE_ENV case

- .editorconfig
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/DOCS.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/MODIFICATION.md
- .github/ISSUE_TEMPLATE/NEW_PLUGIN.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
- README.md
We've moved chat to Discord and are closing down the Gitter. This updates all of the links in this repo.
> docs(repo): update chat/support links

- packages/typescript/src/index.ts
- packages/typescript/src/options/validate.ts
- packages/typescript/test/fixtures/multiple-files/src/index.ts
- packages/typescript/test/fixtures/multiple-files/src/server.ts
- packages/typescript/test/fixtures/multiple-files/tsconfig.json
- packages/typescript/test/test.js
Closes https://github.com/rollup/plugins/issues/247
Please see the description in https://github.com/rollup/plugins/issues/247
> feat(typescript): support multiple output targets with declarations

- packages/node-resolve/README.md
- [ *] documentation
- [* ] no
- [ *] no
It's a small correction in document
> corrected word "yse" to "use"

- .eslintrc.js
- packages/alias/package.json
- packages/alias/types/index.d.ts
- pnpm-lock.yaml
> chore(alias): upgrade TypeScript

- .eslintrc.js
- packages/pluginutils/package.json
- pnpm-lock.yaml
> chore(pluginutils): upgrade TypeScript

- packages/html/recipes/external-files/ReadMe.md
- packages/html/recipes/external-files/index.js
This method provides the ability to reference external css/js files for the generated html, and supports adjusting the file loading sequence.
Method source once issues: https://github.com/rollup/plugins/issues/755
when using it:
```js
import html from '@rollup/plugin-html';
import templateExternalFiles from '@rollup/plugin-html/recipes/external-files';
import postcss from 'rollup-plugin-postcss';
export default [{
input: [ 'demo/demo.ts' ],
output: [ { file: 'dist/demo.js' } ],
plugins: [
postcss({
extract: 'demo.css',
minimize: false,
use: ['sass'],
extensions: ['.scss', '.css'], …
```
> docs (html): recipe for external files in template

- tsconfig.base.json
Adds a bit more safety by removing the `skipLibCheck` flag. It's probably better to do the checking by default and disable only on the projects where it's necessary if a need arises
> Enable TypeScript library checking

- packages/virtual/package.json
- pnpm-lock.yaml
> chore(virtual): upgrade TypeScript

- packages/run/package.json
- pnpm-lock.yaml
> chore(run): upgrade TypeScript

- packages/eslint/package.json
- pnpm-lock.yaml
> chore(eslint): upgrade TypeScript

- packages/data-uri/package.json
- pnpm-lock.yaml
> chore(data-uri): upgrade TypeScript

- packages/buble/package.json
- pnpm-lock.yaml
> chore(buble): upgrade TypeScript

- packages/auto-install/package.json
- pnpm-lock.yaml
> chore(auto-install): upgrade TypeScript

- packages/html/package.json
- pnpm-lock.yaml
> chore(html): upgrade TypeScript

- packages/replace/README.md
This clarifies the function of the replace plugin, based on the concern in #737
> docs(replace): clarify replacement. fixes #737

- packages/babel/README.md
> typo in README.md

- packages/commonjs/src/index.js
- packages/commonjs/src/is-cjs.js
- packages/commonjs/src/proxies.js
- packages/commonjs/test/test.js
List any relevant issue numbers: fixes #869
State was erroneously shared between instances.
> fix(commonjs): idempotence issue

- README.md
List any relevant issue numbers: resolves #873
This corrects the license reference in the readme, resolves #873.
> docs(repo): correct license in readme

- packages/alias/README.md
> alias: Update README.md - fix link

- CODEOWNERS
List any relevant issue numbers: closes #925
Starts a CODEOWNERS file for reasons in #925
This is obviously not everybody, but I'm not sure who actually wants to be in this.
Pinging @rollup/plugin-maintainers @rollup/core 
Please feel free to push commits to the branch
> chore: add a CODEOWNERS

- packages/typescript/package.json
- packages/typescript/src/index.ts
- packages/typescript/src/options/plugin.ts
- packages/typescript/src/options/validate.ts
- packages/typescript/src/outputFile.ts
- packages/typescript/test/fixtures/incremental-single/main.ts
- packages/typescript/test/fixtures/incremental-single/tsconfig.json
- packages/typescript/test/helpers/index.js
- packages/typescript/test/test.js
- packages/typescript/types/index.d.ts
- pnpm-lock.yaml
List any relevant issue numbers: Fixes #698
This PR continues the work started by #859.
> fix(typescript): incremental typescript cache (#859)

- packages/dsv/README.md
I suppose a copy/paste left-over from the `wasm` plugin.
> docs(dsv): remove copypasta from wasm

- packages/sucrase/test/test.js
This is a temporary PR to run CI against and will be closed shortly.
> test(sucrase): investigate windows failures on aliasing

- packages/commonjs/README.md
> docs(commonjs): sync require rollup version

- README.md
`pnpm.js.org` is now `pnpm.io`.
> docs(repo): correct link

- packages/node-resolve/src/resolveImportSpecifiers.js
> chore(repo): fix typo in annotation in node-resolve

- packages/auto-install/README.md
fix readme of auto-install plugin
> docs(auto-install): add pnpm to package manager option

- packages/terser/package.json
- packages/terser/types/index.d.ts
- pnpm-lock.yaml
> fix(terser): bump dependencies

- packages/swc/package.json
- packages/swc/src/module.ts
- pnpm-lock.yaml
> fix(swc): bump dependencies

- packages/esm-shim/package.json
- packages/esm-shim/src/utils.ts
- pnpm-lock.yaml
> fix(esm-shim): bump dependencies

- packages/dynamic-import-vars/README.md
> docs(dynamic-import-vars): typo

- packages/commonjs/README.md
> docs(commonjs): update docs

- packages/commonjs/package.json
- packages/dynamic-import-vars/package.json
- packages/esm-shim/package.json
- packages/inject/package.json
- packages/replace/package.json
- packages/strip/package.json
- pnpm-lock.yaml
This PR updates magic-string from 0.27.0 to 0.30.3. There's some bug fixes.
I think there's no breaking changes included.
https://github.com/Rich-Harris/magic-string/blob/master/CHANGELOG.md
> fix(commonjs,dynamic-import-vars,esm-shim,inject,replace,strip): bump magic-string version

- packages/pluginutils/README.md
> doc(pluginutils): correct the return type of createFilter

- packages/swc/README.md
> docs(swc): add @swc/core to install step

- package.json
- pnpm-lock.yaml
This PR removes unused repo devDependencies.
> chore(repo): remove unused repo devDependencies

- packages/commonjs/package.json
- pnpm-lock.yaml
closes https://github.com/rollup/plugins/issues/1774
Fixes a peer dependency warning
> chore(commonjs): upgrade picomatch

- packages/esm-shim/package.json
- packages/esm-shim/src/constants.ts
- packages/esm-shim/src/index.ts
- packages/esm-shim/src/utils.ts
- pnpm-lock.yaml
This PR should resolve #1842 
1. provide named esm export
2. keep track with `https://github.com/unjs/unbuild/blob/main/src/builders/rollup/plugins/cjs.ts`, so [`findStaticImports`](https://github.com/unjs/mlly/blob/49d9222f27c8e93209480009e2aed0822ad7c01e/README.md#findstaticimports) is used to find index to append code shim, which is implemented with AST. The original `ESMStaticImportRegex` is dropped.
> fix(esm-shim): use `mlly` to find index to append shim
