- README.md
- packages/buble/README.md
- packages/replace/README.md
- Rollup Plugin Name: 
This standardizes the READMEs for plugins on a simple format. 
A note about the ES-level in README snippets: plugins authored in CJS should have CJS in the README. As such, plugins authored with ES6 modules should have ES6 module syntax in the README. That'll be an easy-to-spot standard to follow. Eventually, all plugins should be converted to ESM, but that's a task for another day.
> chore: clean up, standarize readmes

- packages/alias/CHANGELOG.md
- packages/alias/README.md
- packages/alias/package.json
- packages/alias/rollup.config.js
- packages/alias/src/index.js
- packages/alias/test/fixtures/aliasMe.js
- packages/alias/test/fixtures/folder/anotherNumber.js
- packages/alias/test/fixtures/index.js
- packages/alias/test/fixtures/localAliasMe.js
- packages/alias/test/fixtures/nonAliased.js
- packages/alias/test/test.js
- pnpm-lock.yaml
- Rollup Plugin Name: 
This PR migrates the rollup-plugin-alias plugin.
> chore: migrate rollup-plugin-alias

- .gitignore
- packages/alias/README.md
- packages/alias/src/index.js
- packages/alias/test/test.js
- pnpm-lock.yaml
- Rollup Plugin Name: alias
https://github.com/rollup/plugins/issues/14
New feature related to my discussion with @lukastaegert.
`customResolver` option allows to pass plugin or function to be used instead of built-in algorithm for files resolving. Most common expected usage - together with `node-resolve` plugin.
> feat(alias): customResolver instead of built-in resolving algorithm

- packages/alias/README.md
- packages/alias/src/index.js
- packages/alias/test/test.js
- Rollup Plugin Name: 
Adding name to `alias` plugin as recommended inside rollup's plugin development guidelines: https://rollupjs.org/guide/en/#plugin-development
Technically it is a feature? but writing test for it sounds silly. If required I'll gladly add it. :bowtie:
> feat(alias): add plugin name

- README.md
- packages/virtual/CHANGELOG.md
- packages/virtual/README.md
- packages/virtual/package.json
- packages/virtual/rollup.config.js
- packages/virtual/src/index.js
- packages/virtual/test/test.js
- pnpm-lock.yaml
- **Breaking:** Minimum compatible Rollup version is 1.2.0
- **Breaking:** Minimum supported Node version is 8.0.0
This PR merges rollup-plugin-virtual. Pretty basic.
> chore: migrate rollup-plugin-virtual

- packages/buble/index.d.ts
- packages/buble/test/types.ts
- packages/inject/index.d.ts
- packages/inject/test/types.ts
- packages/json/index.d.ts
- packages/json/test/types.ts
- packages/replace/index.d.ts
- packages/replace/test/types.ts
Sometimes we need to have access to `Rollup*Options` interfaces, for example when building a tool in Typescript which wrap Rollup and have a big options object. 
It's something that I've already done for some plugins on DefinitelyTyped repo:
- `rollup-plugin-buble` https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32804
- `rollup-plugin-node-globals` https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32524
- `rollup-plugin-node-resolve` https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32525
The plugin `rollup-plugin-vue` also do the same: https://github.com/vuejs/rollup-plugin-vue/blob/master/src/index.ts#L47
Thanks!
> feat: export Rollup*Options interfaces

- packages/buble/index.d.ts
- packages/buble/package.json
- packages/buble/test/types.ts
- pnpm-lock.yaml
Instead of manually defining types, we use the one from [buble](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/buble/index.d.ts).
Knowing that [the whole options are passed to buble](https://github.com/rollup/plugins/blob/master/packages/buble/src/index.js#L6), I've made `RollupBubleOptions` extends `TransformOptions` (maybe there is a best way to do this?). 
So now we can pass [`jsx`, `Object.assign`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/buble/index.d.ts#L25-L29) and [`namedFunctionExpressions`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/buble/index.d.ts#L57) options too. 
Note that the _old_ and _new_ `TransformOptions` …
> feat(buble): use types from @types/buble

- README.md
- packages/legacy/CHANGELOG.md
- packages/legacy/README.md
- packages/legacy/package.json
- packages/legacy/rollup.config.js
- packages/legacy/src/index.js
- packages/legacy/test/fixtures/.eslintrc
- packages/legacy/test/fixtures/default-export/answer.js
- packages/legacy/test/fixtures/default-export/main.js
- packages/legacy/test/fixtures/named-exports-changed/answer.js
- packages/legacy/test/fixtures/named-exports-changed/main.js
- packages/legacy/test/fixtures/named-exports-nested/answer.js
- packages/legacy/test/fixtures/named-exports-nested/main.js
- packages/legacy/test/fixtures/named-exports-unchanged/answer.js
- packages/legacy/test/fixtures/named-exports-unchanged/main.js
- packages/legacy/test/test.js
- packages/replace/README.md
- pnpm-lock.yaml
This PR migrates the rollup-plugin-legacy plugin.
> chore: migrate rollup-plugin-legacy

- packages/typescript/README.md
List any relevant issue numbers: #72 
Adds instructions for preserving the `jsx: 'preserve'` option which will fail by default if the pluging `acorn-jsx` is not also used.
> docs(typescript): include jsx `preserve` instructions

- packages/typescript/src/index.js
Updates the import path to properly import from `@rollup/pluginutils`.
Fixes #76
> fix(typescript): import from scoped utils

- packages/alias/package.json
- packages/auto-install/package.json
- packages/beep/package.json
- packages/buble/package.json
- packages/dsv/package.json
- packages/html/package.json
- packages/image/package.json
- packages/inject/package.json
- packages/json/package.json
- packages/legacy/package.json
- packages/node-resolve/package.json
- packages/pluginutils/package.json
- packages/replace/package.json
- packages/run/package.json
- packages/strip/package.json
- packages/typescript/README.md
- packages/typescript/package.json
- packages/typescript/src/index.js
- packages/url/package.json
- packages/virtual/package.json
- packages/wasm/package.json
- packages/yaml/package.json
Resolves #75 
- Removes the placeholder `security` script from each plugin's `package.json`
- I verified that `pnpm audit` only uses `pnpm-lock.yaml` to run the audit.
- I installed `lodash@4.17.11` (contains a vulnerability) in the `run` package and `pnpm audit` reported the vulnerability when ran from the repo's root.
- Only adding the vulnerable dependency to `packages/run/package.json` had no effect on `pnpm audit`
- Only adding the vulnerable dependency to `pnpm-lock.yaml` caused the vulnerability to show up during `pnpm audit`
- _Unrelated change: the typescript package had two un-linted files, I've included them here_
> chore: remove placeholder security script from each plugin

- packages/json/package.json
it's current jsnext:main field is pointing to a wrong path, which makes rollup failed to import the plugin
> fix(json): cannot be imported by rollup 

- packages/alias/package.json
- packages/dsv/package.json
- packages/image/package.json
- packages/json/package.json
- packages/legacy/package.json
- packages/node-resolve/package.json
- packages/pluginutils/package.json
- packages/typescript/package.json
- packages/url/package.json
- packages/virtual/package.json
- packages/yaml/package.json
this closes https://github.com/rollup/plugins/pull/81
This PR has two targets:
1. fixes `@rollup/plugin-json` as it's current `jsnext:main` field is pointing to a wrong path, which makes rollup failed to import the plugin
2. remove all `jsnext:main` in favor of `module` as mentioned in https://github.com/rollup/plugins/pull/81#issuecomment-562956077
> chore: remove `jsnext:main` in favor of `module`

- .editorconfig
- README.md
- packages/multi-entry/README.md
- packages/multi-entry/package.json
- packages/multi-entry/rollup.config.js
- packages/multi-entry/src/index.js
- packages/multi-entry/test/fixtures/.eslintrc
- packages/multi-entry/test/fixtures/0.js
- packages/multi-entry/test/fixtures/1.js
- packages/multi-entry/test/fixtures/2.js
- packages/multi-entry/test/test.js
- pnpm-lock.yaml
Migrates `rollup-plugin-multi-entry`.
- Minimum Rollup version ^1.20.0
- Changes entry tag
> chore: migrate rollup-plugin-multi-entry

- packages/pluginutils/src/createFilter.ts
- packages/pluginutils/test/createFilter.ts
Fixes #80
Escapes some special characters for globs that can appear in paths.
> fix(pluginutils): Escape glob characters in folder

- README.md
- packages/run/index.d.ts
- packages/run/package.json
- pnpm-lock.yaml
Adds TypeScript types for the `@rollup/plugin-run` plugin, as well as links to it from the README.
> Add typings to `run`

- packages/commonjs/CHANGELOG.md
- packages/image/CHANGELOG.md
- packages/legacy/CHANGELOG.md
- packages/node-resolve/CHANGELOG.md
- packages/pluginutils/CHANGELOG.md
- packages/sucrase/CHANGELOG.md
- packages/typescript/CHANGELOG.md
- packages/url/CHANGELOG.md
- packages/virtual/CHANGELOG.md
A bunch of changelogs list '1.2.0' as the new minimum Rollup version, when they should say '1.20.0'.
> chore: fix minimum Rollup version in several changelogs

- packages/alias/README.md
- packages/buble/README.md
- packages/commonjs/README.md
- packages/image/README.md
- packages/inject/README.md
- packages/json/README.md
- packages/node-resolve/README.md
- packages/pluginutils/README.md
- packages/replace/README.md
- packages/strip/README.md
- packages/sucrase/README.md
- packages/typescript/README.md
- packages/url/README.md
- packages/wasm/README.md
- packages/yaml/README.md
List any relevant issue numbers: #106
Normalize how arrays are represented
> Normalize Array format in README

- packages/typescript/src/index.ts
- packages/typescript/src/options.ts
- packages/typescript/test/test.js
Moving from `console.error` to `this.warn`. Additionally cleaned up the options slightly by isolating mutations and extracting some code to helper functions.
> fix(typescript): Use this.warn for ts errors

- packages/virtual/README.md
The import path of the virtual plugin in the readme is still the one before it moved to this monorepo. I fixed it.
> fix typo in virtual plugin

- packages/alias/CHANGELOG.md
- packages/auto-install/CHANGELOG.md
- packages/beep/CHANGELOG.md
- packages/buble/CHANGELOG.md
- packages/commonjs/CHANGELOG.md
- packages/dsv/CHANGELOG.md
- packages/html/CHANGELOG.md
- packages/image/CHANGELOG.md
- packages/inject/CHANGELOG.md
- packages/json/CHANGELOG.md
- packages/legacy/CHANGELOG.md
- packages/multi-entry/CHANGELOG.md
- packages/node-resolve/CHANGELOG.md
- packages/pluginutils/CHANGELOG.md
- packages/replace/CHANGELOG.md
- packages/run/CHANGELOG.md
- packages/strip/CHANGELOG.md
- packages/sucrase/CHANGELOG.md
- packages/typescript/CHANGELOG.md
- packages/url/CHANGELOG.md
- packages/virtual/CHANGELOG.md
- packages/wasm/CHANGELOG.md
- packages/yaml/CHANGELOG.md
In conjunction with #133, this PR asserts that changelogs exist and use the same title format. These changes are key to the auto-changelog-generation process.
> chore(repo): assert changelogs

- packages/auto-install/test/yarn-bare.js
- packages/auto-install/test/yarn.js
- pnpm-lock.yaml
- pnpm-workspace.yaml
I've noticed that the currently used pattern was overly greedy and has classified such things as potential packages:
```
packages/auto-install/test/fixtures/npm
packages/auto-install/test/fixtures/yarn
packages/auto-install/test/fixtures/yarn-bare
packages/json/test/fixtures/named
packages/node-resolve/test/fixtures
```
Things were working, but including those as workspace packages was not intentional so better to fix that.
> chore: change workspace packages pattern

- packages/node-resolve/README.md
More clear doc related to mainFields priority and distinct options for browser, module, jsnext and main. Rework markup to distinguish values of mainFields and corresponding values in package.json.
> docs(node-resolve): improve doc related to mainFields

- packages/url/src/index.js
- packages/url/test/test.js
As with a few other plugin tests, the recent change in Github Actions' Windows image/pipeline was causing `@rollup/plugin-url` to fail tests on Windows. After looking into it, the plugin would have been fairly unusable on Windows. Previously, the tests were passing the Windows Github Actions - somehow. This change addresses Windows file paths and normalizes paths that need to be.
Because this is a critical flaw, this will be merged with or without review after 12 hours.
> fix(url): windows compatible, tests

- packages/commonjs/package.json
List any relevant issue numbers: Fixes #83
This is the last of the `jsnext:main` package.json entries that needs to be cleaned up. It's not technically breaking since the `module` field has existed beside it for several versions.
> chore(commonjs): remove jsnext:main

- packages/typescript/src/options.ts
- packages/typescript/test/fixtures/tsconfig-extends/ts-config-extends-child/main.tsx
- packages/typescript/test/fixtures/tsconfig-extends/ts-config-extends-child/tsconfig.json
- packages/typescript/test/test.js
This plugin has `extends` option support  but plugin does not give the right extended config file path.
For example: If your tsconfig contains `"extends": "../generic-tsconfig.json"` typescript plugin looks parent directory of project root folder because of the dots.
I added proper path resolver to fix this bug.
UPDATE: Bug happens when tsconfig option given.
> fix(typescript) extended config file path

- packages/json/index.d.ts
The type definitions don't match the docs, or the plugin behavior. When used with TypeScript, you can't call the plugin without explicitly including these options which are meant to be optional. And `namedExports: false` was literally not allowed.
> Update type definitions

- packages/commonjs/README.md
The link to `plugin-node-resolve` was broken (https://github.com/rollup/plugins/packages/node-resolve). This PR updates the link URL to resolve to the correct place (https://github.com/rollup/plugins/tree/master/packages/node-resolve).
> Fix link for plugin-node-resolve

- packages/alias/README.md
List any relevant issue numbers: #174 
Changing label to @rollup/plugin-node-resolve  and link to https://www.npmjs.com/package/@rollup/plugin-node-resolve
> docs(alias): Fix reference to plugin-node-resolve

- packages/typescript/src/index.ts
- packages/typescript/src/options.ts
- packages/typescript/src/tslib.ts
- packages/typescript/test/test.js
- packages/typescript/tsconfig.json
Refactors the option parsing to rely more on the Typescript API. `ParsedCommandLine` will later be used for plugin improvements as it includes additional data.
This is the first part of getting typechecking to work for the plugin. For that reason, we set up the `fileNames` array in this PR even though its not used _yet_.
> chore(typescript): Always use ParsedCommandLine

- packages/pluginutils/src/index.ts
fixes #171
For some reason, those exports were moved to an exported as default object - but all (most?) existing consumers expect named exports for those (and I also believe that named exports are just better suited here).
> fix(pluginutils): bring back named exports

- packages/pluginutils/src/createFilter.ts
- packages/pluginutils/test/createFilter.ts
(will need to look those up if some exist, sorry)
This fixes a regression between pluginutils@3.0.2 and @3.0.3 where a pattern starting with `./` would no longer match because it would just be concatenated with the base path to something like `/base/path/./my/path`.
This problem came up in rollup-plugin-node-resolve because this (correctly) uses `createFilter` to resolve package sideEffect specifications. These specifications however tend to use relative paths, hence the issue. Basically this was breaking the package side-effects feature.
Simple example:
```js
createFilter(['./index.js'])
filter(resolve('index.js')) // false before this PR, true afterwards
```
> fix(pluginutils): resolve relative paths starting with "./"

- packages/data-uri/package.json
- packages/data-uri/tsconfig.json
- packages/pluginutils/package.json
- packages/pluginutils/rollup.config.js
- packages/pluginutils/src/attachScopes.ts
- packages/pluginutils/src/dataToEsm.ts
- packages/pluginutils/src/extractAssignedNames.ts
- packages/pluginutils/tsconfig.json
- packages/pluginutils/types/index.d.ts
- packages/typescript/package.json
- packages/typescript/src/diagnostics.ts
- packages/typescript/src/documentRegistry.ts
- packages/typescript/src/host.ts
- packages/typescript/src/index.ts
- packages/typescript/src/options.ts
- packages/typescript/src/tslib.ts
- packages/typescript/tsconfig.json
- pnpm-lock.yaml
- tsconfig.base.json
Now that the new Typescript plugin is released lets start using it for typechecking our plugins! 
I've worked to normalize the tsconfig settings we use across the different plugins. The es2017 target was chosen because its the highest that Node 8 supports. The `src` glob is used so that VSCode and other IDEs can tell that a tsconfig file affects the corresponding plugin.
estree-walker doesn't export the `Node` type so its imported from `@types/estree` instead. I use an inline import because ESLint complains about importing a module we don't depend on.
> chore: Use typechecking with some plugins

- packages/node-resolve/src/util.js
- packages/node-resolve/test/order.js
- https://github.com/rollup/plugins/issues/195
In 7.1.0 while refactoring main fields were reordered which caused a regression.
> fix(node-resolve) main fields regression

- .gitignore
- packages/typescript/src/options.ts
- packages/typescript/test/fixtures/tsconfig-extends-module/main.tsx
- packages/typescript/test/fixtures/tsconfig-extends-module/node_modules/shared-config/package.json
- packages/typescript/test/fixtures/tsconfig-extends-module/node_modules/shared-config/tsconfig.json
- packages/typescript/test/fixtures/tsconfig-extends-module/tsconfig.json
- packages/typescript/test/test.js
List any relevant issue numbers: #70 
Adds test for extending a node module in tsconfig.json. 
Passing the path to `parseJsonConfigFileContent` means that we don't need the previous `extends` fix, so we can fully rely on built-in Typescript behaviour.
> fix(typescript): Use builtin extends resolution

- packages/typescript/test/fixtures/optional-chaining/main.ts
- packages/typescript/test/test.js
List any relevant issue numbers: #205 
Adds Test case for optional chaining (and nullish coalescing)
> test(typescript): Add test for optional chaining

- packages/typescript/src/diagnostics/emit.ts
- packages/typescript/src/diagnostics/host.ts
- packages/typescript/src/diagnostics/toWarning.ts
- packages/typescript/src/host.ts
- packages/typescript/src/index.ts
- packages/typescript/src/moduleResolution/host.ts
- packages/typescript/src/moduleResolution/resolver.ts
- packages/typescript/src/options.ts
- packages/typescript/test/test.js
Separates the host object. This makes it easier for me to try out different compiler APIs as I don't need to refactor a single object every time.
> chore(typescript): refactor compiler host

- packages/pluginutils/package.json
- packages/pluginutils/rollup.config.js
- pnpm-lock.yaml
Moving from rollup-* to \@rollup/* and making micromatch an external dependency.
Micromatch was bundled for Node 6 compatibility, but we no longer support that version. Unbundling it can help with tree shaking.
> chore(pluginutils): Don't bundle micromatch

- packages/commonjs/src/transform.js
- packages/commonjs/test/fixtures/samples/define-property/foo.js
- packages/commonjs/test/fixtures/samples/define-property/main.js
- packages/commonjs/test/test.js
This pr adds exports that have been defined using the `Object.defineProperty(exports, ...)` technique. I was running into an issue with a 3rd party lib (`@material-ui/core@3.9.4`) where it was using this technique to define the exports. Rollup was falling over with the error `export 'foo' is not exported by 'path/to/module'`.
> feat(commonjs): export properties defined using Object.defineProperty(exports, ..)

- packages/typescript/test/fixtures/preserve-modules/main.ts
- packages/typescript/test/fixtures/preserve-modules/tsconfig.json
- packages/typescript/test/test.js
List any relevant issue numbers: #232
Adds tests to make sure the changes in version 4.0.0 fix the preseveModules issue.
> test(typescript): Add preserveModules test

- packages/run/lib/index.js
- packages/run/test/test.js
In bundle assets are placed before entry point and run plugin fails with
```
@rollup/plugin-run requires Rollup 0.65 or higher
```
> fix(run): Support assets

- package.json
- packages/alias/package.json
- packages/alias/test/test.js
- packages/auto-install/package.json
- packages/beep/package.json
- packages/buble/package.json
- packages/commonjs/package.json
- packages/commonjs/test/test.js
- packages/data-uri/package.json
- packages/dsv/package.json
- packages/html/lib/index.js
- packages/html/package.json
- packages/image/package.json
- packages/inject/package.json
- packages/json/package.json
- packages/legacy/package.json
- packages/multi-entry/package.json
- packages/node-resolve/package.json
- packages/pluginutils/package.json
- packages/replace/package.json
- packages/run/package.json
- packages/strip/package.json
- packages/sucrase/package.json
- packages/typescript/package.json
- packages/url/package.json
- packages/virtual/package.json
- packages/wasm/package.json
- packages/yaml/package.json
- pnpm-lock.yaml
I did a complete review of all plugins against all breaking changes in Rollup 2. My findings:
hardly anything needed to be done. Only plugin-html may trigger a deprecation warning when accessing `isAsset` until the next release, but I would not see it as severe enough to delay releasing Rollup 2.
Furthermore, plugin-alias needed some test adaptations as
- modules without own code no longer show up in the output
- a warning message has changed
Lastly, I updated the imported Rollup dev dependency and all peer dependency version ranges for Rollup so users do not see warnings. IMO all updates could be patches.
> Audit for Rollup@2.0.0

- packages/html/package.json
List any relevant issue numbers: none
Fixes an incorrect homepage url inside `package.json` that is displayed on https://npmjs.com/
> Fix wrong homepage url for html plugin

- .editorconfig
- package.json
- packages/run/lib/index.js
Basically hard to create test on race condition, we have situation that 80% of our developers
has no issue at all as bundle has written to disk before fork, and other 20% sometimes can't start app at all
Description:
At the moment of fork inside run, there is possible that bundle file is not created at the moment. Or is in the process of writing. This cause fork to break without any errors.
PS:
also fixed editorconfig as its not in sync with eslint rules
> Fix run plugin could fork before bundle generated

- packages/run/src/index.ts
- packages/run/test/fixtures/facade-entry/dynamic.js
- packages/run/test/fixtures/facade-entry/index.js
- packages/run/test/fixtures/facade-entry/library.js
- packages/run/test/test.js
Ref https://github.com/rollup/plugins/pull/241#issuecomment-605697947
- take input from latest options when build is started
- check facade id instead of modules list
> fix(run): use correct hook for reading options, handle facade chunks

- packages/buble/package.json
- packages/commonjs/package.json
- packages/multi-entry/package.json
- packages/node-resolve/package.json
- packages/url/package.json
- packages/yaml/package.json
- pnpm-lock.yaml
> actually this kinda does not apply because this is not a code change, only dependencies upgrades
babel/babel#11216
The first intention was to upgrade `buble` in `@rollup/plugin-buble` because of a npm audit warning:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ acorn                                                        │ …
```
> Upgrade buble and issue babel/babel#11216

- packages/node-resolve/src/util.js
- packages/node-resolve/test/fixtures/symlinked/second/index.browser.js
- packages/node-resolve/test/fixtures/symlinked/second/package.json
- packages/node-resolve/test/symlinks.js
The regression appeared here https://github.com/uuidjs/uuid/pull/402#discussion_r400711937
after upgrading from `rollup-plugin-node-resolve` to `@rollup/plugin-node-solve`
Dependencies entry points are resolved into symlinked path when browser
field map contains real paths.
> node-resolve: resolve symlinked entry point properly

- packages/typescript/src/options/normalize.ts
- packages/typescript/test/test.js
- util/test.js
> Fix typescript sourcemap generated as null

- packages/virtual/README.md
While possible, it's not obvious that the `virtual` plugin can pass a string of code to Rollup's input. 
This little example makes this obvious, specially for Rollup beginners.
> Add example for passing code to Rollup's input

- packages/wasm/src/index.js
- packages/wasm/test/fixtures/worker.js
- packages/wasm/test/test.js
The code generated by @rollup/plugin-wasm breaks when executed in a
service worker because window is undefined.
- [] no
~~This is a draft PR because I'm not sure how to write a test that runs code inside a service worker. Once I figure that out, I will add a test and update the above checkbox.~~
List any relevant issue numbers: #333 
~~This PR adds a check for whether `window` is undefined.~~ This PR makes the loader function use `globalThis` instead of `window`. Prior to this, `@rollup/plugin-wasm` would break when the resulting generated code was run in a service worker, because it assumed `window` was defined.
> Make wasm plugin work with service workers

- packages/node-resolve/src/index.js
- packages/node-resolve/test/fixtures/only-local.js
- packages/node-resolve/test/fixtures/only.js
- packages/node-resolve/test/only.js
- util/test.d.ts
- util/test.js
This PR fixes the issue #209, where using the `resolveOnly` option at the `node-resolve` plugin prevented the resolution of local modules.
> fix(node-resolve): Resolve local files if `resolveOption` is set

- packages/babel/CHANGELOG.md
When upgrading from 4.X to 5.0.0, it was difficult to find out why `runtimeHelpers` no longer worked because it didn't appear in an informative CHANGELOG entry. After seeing this line, it was clear. This will hopefully help others upgrade more easily!
> fix(babel): Correct breaking change note in 5.0 CHANGELOG

- packages/babel/src/transformCode.js
fixes #345
It got missed when `transform` has been migrated to `transformAsync`.
I don't think this change is worth testing now because it can only be tested on node@13+.
> fix(babel): use loadPartialConfigAsync when it is available

- packages/commonjs/README.md
- packages/commonjs/src/index.js
- packages/commonjs/test/fixtures/form/unambiguous-with-default-export/_config.js
- packages/commonjs/test/fixtures/form/unambiguous-with-import/_config.js
- packages/commonjs/test/fixtures/form/unambiguous-with-named-export/_config.js
- packages/commonjs/test/fixtures/function/dynamic-require-code-splitting/_config.js
- packages/commonjs/test/fixtures/function/dynamic-require-es-entry/_config.js
- packages/commonjs/test/fixtures/function/es6-export-with-global-sniffing/_config.js
- packages/commonjs/test/types.ts
- packages/commonjs/types/index.d.ts
List any relevant issue numbers: #348, #342
Reverts default behavior of mixed es and cjs modules.  
I have marked this as a  "breaking change", but the PR that raised this need was a actually a breaking change for people who did not utilize `include`/`exclude` correctly and have garbage of mixed UMD mechanisms.
> feat(commonjs): add kill-switch for mixed es-cjs modules

- packages/babel/README.md
> docs(babel): Cleanup misleading leftovers in the README

- packages/typescript/README.md
It used to have outdated imports.
README of `@rollup/plugin-typescript` used to have outdated imports in the examples.
> docs(typescript): fixes readme examples

- packages/node-resolve/src/index.js
- packages/node-resolve/types/index.d.ts
Building on #301, this updates the documentation but also re-adds a default export. When the plugin is used with ES modules, the previous change is no longer a breaking change. However, CommonJS modules still must switch to named exports.
For consistency we should always used named exports in the documentation, but this helps users migrate to the new format.
> feat(node-resolve): Add default export

- packages/wasm/README.md
- packages/wasm/package.json
- packages/wasm/rollup.config.js
- packages/wasm/src/index.ts
- packages/wasm/test/test.js
- packages/wasm/types/index.d.ts
- pnpm-lock.yaml
- shared/rollup.config.js
- util/test.d.ts
- util/test.js
BREAKING CHANGES: Named exports are used for CJS
List any relevant issue numbers: #360
Switch to Typescript for the wasm plugin. I chose to also switch to named exports here, but that could be pulled out to a separate PR.
> feat(wasm): Switch to TypeScript & named exports

- packages/babel/README.md
Update `babelHelpers` options documentation, which was confusing (and likely incorrect): it reported that `babelHelpers: 'inline'` is the default, when the header of the section says that the default is `'bundled'`.
Please verify that this documentation change reflects the actual behavior.
> docs(babel): update babelHelpers default description

- packages/commonjs/types/index.d.ts
As the commit message, `namedExports` option of `@rollup/plugin-commonjs` is deprecated, so remove it from related types.
> `namedExports` is now deprecated

- packages/pluginutils/package.json
- packages/pluginutils/rollup.config.js
- shared/rollup.config.js
- https://github.com/rollup/plugins/issues/412
- https://github.com/rollup/plugins/pull/413
Enable native node es modules via "exports" field in package.json.
Added custom plugin to generate nested package.json with `{"type": "module"}`
as an alternative to mjs extension usage. This works similar to rollup distribution.
https://unpkg.com/browse/rollup@2.10.9/dist/es/
This change is necessary before migrating all other plugins.
> feat(pluginutils): add native node es modules support

- packages/replace/README.md
#399 
This PR updates the documentation as stated in #399 to clarify that functions can be used as replacement options using the replace plugin.  Testing revealed that replacing with numbers also works, so I changed the wording _strings_ into _primitives_ (unsure if that's a good term ?)
> docs(replace): clarify options for allowed replacement values

- packages/alias/src/index.ts
- packages/alias/test/test.js
- packages/alias/types/index.d.ts
Resolves #203 
This will make sure that for all custom resolvers
- the `buildStart` hooks are run if present during `buildStart`
- the `resolveId` hook is run with correct `this` context
> fix(alias): properly initialize custom resolvers

- packages/json/src/index.js
- packages/json/test/test.js
Helpful when debugging
Sometimes in a large codebase, a single comma buried in a gigantic json file can halt the entire build. This change ensures that users will more easily be able to find and fix those errors.
> feat(json): log the filename when JSON.parse fails

- packages/url/src/index.js
Conform to Rollup type definitions to silence compiler errors, as they expect a plugin name and it's [expected/advised](https://rollupjs.org/guide/en/#plugins-overview) on the docs. 
Current workaround is: 
```ts
{
name: "url",
...url({
limit: 0,
include: defaultAssetTypes,
fileName: '[dirname][name]_[hash][extname]',
sourceDir: path.join(__dirname, 'src')
})
},
```
or more succinct and error prone: 
```ts
url({
limit: 0,
include: defaultAssetTypes,
fileName: '[dirname][name]_[hash][extname]',
sourceDir: path.join(__dirname, 'src')
}) as any,
```
~~Also, exporting defaultInclude as I'd like to extend the defaults instead of redefining them.~~
Edit: Got rid of that, since I guess you don't want to mix default and named export, …
> fix(url): Conform to Rollup type definitions.

- packages/node-resolve/package.json
- packages/node-resolve/rollup.config.js
- https://github.com/rollup/plugins/issues/412
Wrapper module is the simplest solution. I used it in terser plugin
which cannot resolve worker without commonjs for now.
> feat(node-resolve): add native node es modules support

- packages/typescript/src/index.ts
- packages/typescript/test/fixtures/reexport-type/Baz.ts
- packages/typescript/test/fixtures/reexport-type/main.ts
- packages/typescript/test/test.js
The plugin ignores files which are emitted empty. In this cases Rollup deals with original source code and may fail with SyntaxError.
My case:
- `export *` from file with types only (that file has empty emit output)
- TS 3.9 (`export *` is always retained)
I used type-reexporting test case to reproduce. The existing version passes because sourceMap is enabled. TS emits single sourceMappingURL comment and plugin accepts it. Test fails when sourceMap is disabled.
I've also extended test case with `export *` declaration.
> fix(typescript): load empty emitted files

- packages/typescript/package.json
- packages/typescript/src/index.ts
- packages/typescript/src/watchProgram.ts
- pnpm-lock.yaml
BREAKING CHANGES: Changed `rollup` peer dependency to `rollup@^2.14.0`
https://github.com/rollup/rollup/issues/3608
#418
Fix: #478
I applied `prettier` and added the new `this.meta.watchMode` (see https://github.com/rollup/rollup/pull/3616). Checking `process.env.ROLLUP_WATCH` will only work in `rollup -w` context. Checking for `this.meta.watchMode` will also work in `rollup.watch` context. In the future plugins should preferable utilize `this.meta.watchMode`.
> fix(typescript): utilize 'this.meta.watchMode'

- packages/node-resolve/README.md
The valid value for `mainFields` should be `jsnext:main` instead of `jsnext`.
> docs(node-resolve): Fix mainFields valid values

- package.json
- packages/node-resolve/package.json
- packages/node-resolve/src/index.js
- packages/node-resolve/test/browser.js
- packages/node-resolve/test/fixtures/ts-import-js-extension/import-ts-with-js-extension.ts
- packages/node-resolve/test/fixtures/ts-import-js-extension/main.ts
- packages/node-resolve/test/test.js
- pnpm-lock.yaml
Closes https://github.com/rollup/plugins/issues/479
https://github.com/rollup/plugins/issues/479
As described in #479 it's common for a TS project to use '.js' to refer to local '.ts' or '.tsx' files. This adds support for that.
Previously/Currently you need to import as either `'./file'` (see quote in #479 :wink:) or `'./file.ts'`. Both don't really work:
The fix:
I haven't added tests because it's only 5 lines of code and the "algorithm" is just "Is a TS/TSX file importing a JS file and `{ extensions: [] }` has TS and/or TSX in it? Then add to `importSpecifierList` as a …
> Support TypeScript `.js` imports

- packages/commonjs/src/transform.js
- packages/commonjs/test/fixtures/form/ndoe-require-methods/input.js
- packages/commonjs/test/fixtures/form/ndoe-require-methods/output.js
#406 
Prevent commonjs plugin rewrite Nodejs original `require` methods.
> feat(commonjs): prevent rewrite require.resolve

- packages/node-resolve/src/index.js
- packages/node-resolve/test/fixtures/hash.js
- packages/node-resolve/test/fixtures/search-params-and-hash.js
- packages/node-resolve/test/fixtures/search-params.js
- packages/node-resolve/test/test.js
List any relevant issue numbers: Fixes https://github.com/rollup/plugins/issues/486
This makes node-resolve preserve any search params or hashes if they were in the import path.
Code:
```js
import foo from 'my-package?foo=bar';
```
Before this change it would throw, saying it can't find `my-package?foo=bar'`.
After this change, it gets resolved to something like:
```js
import foo from '/absolute/file/system/path/to/my-package?foo=bar';
```
This would still throw as rollup tries to find this file, but a rollup plugin can set up a special load for a module with this parameter.
> feat(node-resolve): preserve search params and hashes

- packages/dynamic-import-vars/README.md
- packages/dynamic-import-vars/src/dynamic-import-to-glob.js
- packages/dynamic-import-vars/test/src/dynamic-import-to-glob.test.js
no issue was specifically created for this, we had one in the original repo: https://github.com/LarsDenBakker/rollup-plugin-dynamic-import-variables/issues/1
This PR enhances the `@rollup/dynamic-import-vars` plugin with support for some extra patterns for the vars.  
In some cases, during a Rollup build, it is needed to do a Babel transformation to support older browsers. When transofrming template literals, this means this type of code ``import(`./translations/${foo}.js`)`` becomes ``import('./translations/'.concat(foo, '.js'))``. If this happens before the `@rollup/dynamic-import-vars` plugin, the plugin won't be able to expand the code anymore. This PR adds the required code to support this type …
> feat(dynamic-import-vars): add support for dynamic expressions with concat

- packages/babel/package.json
- packages/babel/src/index.js
I can't add tests yet because Babel 7.11 is not yet published.
`@babel/preset-env` 7.11 will support `export * as ns`(https://github.com/babel/babel/pull/11849), where a new caller support flag `supportsExportNamespaceFrom` is introduced. This PR declares this flag so Babel can skip `export-namespace-from` transform when it is bundled from Rollup.
The Rollup 1 peer dependence is bumped to [1.26.0](https://github.com/rollup/rollup/releases/tag/v1.26.0), in which `export * as ns` was initially supported.
> feat(babel): `export * as ns` support

- packages/pluginutils/README.md
The current docs say that `createFilter` uses minimatch, but it actually uses picomatch.
https://github.com/rollup/plugins/blob/5fa15590e452d568239a6d8e1c7018865c027fe4/packages/pluginutils/src/createFilter.ts#L3
The differences are pretty subtle, but I think it's important to document them for people with more specific use cases, and for people creating packages that depend on `createFilter`.
> Correct minimatch to picomatch in the docs

- packages/multi-entry/README.md
- packages/multi-entry/package.json
- packages/multi-entry/src/index.js
- packages/multi-entry/test/test.js
- pnpm-lock.yaml
Prompted by #488 
Fixes Windows related error and exposes new option for overriding defaults.
Idea for this PR from #506 
BREAKING CHANGES: Outputs a multi-entry file with different default name
Refactored multi-entry to use plugin-virtual for resolving/loading the multiple entries into a single entry file. Some tidy-up and adding a new option, `entryFileName`, to override the default entry filename.
First PR for rollup, feel free to provide feedback and further notes for work.
> refactor(multi-entry): virtualised & entryFileName

- packages/pluginutils/src/createFilter.ts
- packages/pluginutils/test/createFilter.ts
List any relevant issue numbers: Fixes https://github.com/rollup/plugins/issues/490
When a pattern is an absolute path or when it starts with a glob star, the current working directory is not prefixed.
If a pattern is an absolute pattern: `/Users/me/some/path/to/code.js`, the pattern becomes `/Users/me/some/path/Users/me/some/path/to/code.js` which is a useless path. 
If a pattern starts with a glob, like: `**/*` the user's intent is to clearly match all parent directories. This becomes: `/Users/me/some/path/**/*`, and the user (unknowingly) does not include or exclude files outside of the current working …
> fix(pluginutils)!: don't add cwd to absolute or patterns that start with a glob

- packages/node-resolve/package.json
- packages/node-resolve/src/index.js
- pnpm-lock.yaml
This 2 dependencies are currently used to deepfreeze an exported symbol. Which seems to be an wasteful to add 2 extra dependencies for something trivial.
Also `deep-freeze` is licensed as Public Domain, which might be problematic for some 3rd parties such as the Angular CLI.
In Angular CLI we have a license validator that validates direct and transitive dependencies, and Public Domain is a problematic license becuse it falls under the "unencumbered' group which requires legal audit.
More context: https://opensource.google/docs/thirdparty/licenses/#unencumbered
> refactor(node-resolve): remove deep-freeze and deepmerge from dependencies

- packages/babel/src/index.js
When a person upgrades from earlier version of `@rollup/plugin-babel` (say, [from the time of `rollup-plugin-babel` for a use-case such as the one in this issue](https://github.com/rollup/rollup-plugin-babel/issues/322)) which used `runtimeHelpers`, gets into error somewhere between other errors and unexpected outputs with a behavior change.
I wished, as a user of this fine package, that the error message would've told me about the variable name change.
> docs(babel): Add warning to tell about configuration name change runtimeHelpers -> babelHelpers

- packages/typescript/test/fixtures/declaration-root-dir/src/main.ts
- packages/typescript/test/fixtures/declaration-root-dir/tsconfig.json
- packages/typescript/test/test.js
This PR relates to https://github.com/rollup/plugins/issues/287 and adds working example of declarations being generated with non-default `rootDir` specified. This PR might also be supplemented by failing test and additional input configs validation as described in this comment https://github.com/rollup/plugins/issues/287#issuecomment-678757955.
> test(typescript): add generating declarations with non-default rootDir

- packages/typescript/README.md
- packages/typescript/src/options/interfaces.ts
- packages/typescript/test/fixtures/syntax-error/tsconfig.json
BREAKING CHANGE: `noEmitOnError` now defaults to false instead of true. This means that Rollup will show a warning when type errors are encountered but will still compile. The previous behaviour is available by changing the setting to `true`.
For watch mode to work, warnings must be used instead of errors. This behaviour better matches how Typescript works, since it only warns for type errors but compiles anyways. However, its different from how bundlers like Webpack work, as they usually fail.
> fix(typescript): Change `noEmitOnError` default to false

- packages/pluginutils/README.md
- packages/pluginutils/src/createFilter.ts
- packages/pluginutils/src/index.ts
- packages/pluginutils/src/normalizePath.ts
- packages/pluginutils/test/createFilter.ts
- packages/pluginutils/test/normalizePath.ts
- packages/pluginutils/types/index.d.ts
This PR includes:
1. A new utility `normalizePath`.
2. Fixes a bug on Windows. On Windows 10, test failed because `path.resolve` creates patterns including backward slash `\`. This patch adds a normalization similar to `createFilter`:
https://github.com/rollup/plugins/blob/55a9cb20d7686750aa104d6a45a7d6834f57ba4a/packages/pluginutils/src/createFilter.ts#L15-L17
3. Small quotes typo in README.
> feat(pluginutils): normalizePath

- packages/commonjs/types/index.d.ts
add `requireReturnsDefault` to `types/index.d.ts`
> feat(commonjs): add requireReturnsDefault to types

- packages/typescript/types/index.d.ts
I noticed while trying to debug an error that the docstring for the `exclude` field was (erroneously) the same as the `include` field. That's all.
> Clarify docstring

- packages/node-resolve/src/index.js
- packages/node-resolve/test/fixtures/hash-in-path.js
- packages/node-resolve/test/fixtures/hash.js
- packages/node-resolve/test/fixtures/node_modules/test/#/foo.js
- packages/node-resolve/test/test.js
This PR is fixing https://github.com/rollup/plugins/issues/587
```
import test from 'test#foo'
```
treats as hash usage
```
import test from 'test/#/foo'
```
treats `hash` as part of package path
> fix(node-resolve): resolve hash in path

- packages/wasm/src/helper.ts
- packages/wasm/src/index.ts
- packages/wasm/test/fixtures/foo.js
- packages/wasm/test/fixtures/injectHelper.js
- packages/wasm/test/test.js
For now, `wasm` plugin is using `banner` API to inject helper function `_loadWasmModule`, but it will inject this helper function in every file, even those files is unrelated to wasm things.
After this PR merged, it uses a helper module to inject `_loadWasmModule`, hopes to help removing the redundant code
> refact(wasm): use helper module instead of banner

- packages/pluginutils/package.json
- packages/pluginutils/test/attachScopes.ts
- pnpm-lock.yaml
List any relevant issue numbers: #547
Generate AST with acorn as #547 suggested. This helps us include more complex tests in the future.
> refactor(pluginutils): improve readability of attachScopes test

- packages/yaml/README.md
- packages/yaml/src/index.js
- packages/yaml/test/test.js
Non-breaking change since people don't have to use the extra transformer argument.
Reason for this change: I need to apply different content transformations depending on which file the data came from. Without knowing the file, the transformer function has to rely on brittle heuristics to identify the file based on its content (which can obviously change over time).
I think a new test case isn't needed for this but happy to provide one if someone thinks otherwise.
> yaml plugin: provide file id to transform function

- packages/pluginutils/package.json
- packages/pluginutils/src/attachScopes.ts
- packages/pluginutils/test/attachScopes.ts
- pnpm-lock.yaml
List any relevant issue numbers: Fixes #547, fixes #548, fixes #549
This PR adds a new behavior to `attachScopes`. It creates a new scope object for `ForStatement`, `ForInStatement`, and `ForOfStatement`. IDK if this should be considered as a breaking change.
> fix(pluginutils): attach scope object to for-loop

- packages/typescript/src/options/validate.ts
- packages/typescript/test/test.js
List any relevant issue numbers: -
TypeScript's `composite` compiler option produces declaration files, too. I stumbled upon this and did get a generic validation error right at the end when the plugin wants to print the files to the outdir but cannot find one. To fix it, I added an additional check to the relevant validation.
> fix(typescript): add composite to validation checks

- packages/typescript/src/options/validate.ts
- packages/typescript/test/test.js
List any relevant issue numbers: -
As a Rollup novice I had some problems figuring out what some of the error messages meant. More specifically, I did not know what options they talked about, so I added more context, telling if it's either a Rollup or TS compiler option.
> docs(typescript): More informative error messages

- packages/babel/package.json
- packages/babel/src/index.js
- packages/babel/src/utils.js
- packages/babel/test/as-input-plugin.js
- packages/babel/test/fixtures/with-query-and-hash/main.js
- packages/babel/test/fixtures/with-query-and-hash/module#Hash.js
- packages/babel/test/fixtures/with-query-and-hash/moduleQuery.js
- packages/babel/test/fixtures/with-query-and-hash/moduleQueryAnd#Hash.js
- pnpm-lock.yaml
List any relevant issue numbers: Fix: https://github.com/rollup/plugins/issues/500
When babel plugin is filtering module by file extensions, it should consider paths that contains hash and query param, and strip them out before doing file extension matching.
The motivation and implementation is similar to [how node-resolve plugin support hash and query](https://github.com/rollup/plugins/pull/487).
> fix(babel): strip hash and query param in extension filter

- packages/typescript/README.md
Fixed a broken bullet point and wrong single quote characters.
> Fix minor markdown syntax in transformers-section

- packages/babel/src/bundledHelpersPlugin.js
I don't really have a failing test for this and I don't think it's worth testing any implementation details to just have this verified. Usually one doesn't have to worry about inserting duplicated nodes but it's a good practice to never do this and always insert fresh nodes.
> fix(babel): clone cached helper identifier before returning it

- packages/typescript/src/index.ts
- packages/typescript/test/fixtures/normalize-ids/one.js
- packages/typescript/test/fixtures/normalize-ids/tsconfig.json
- packages/typescript/test/fixtures/normalize-ids/two.js
- packages/typescript/test/test.js
List any relevant issue numbers: #643
Fix #643 by normalizing module ids to use host os separators before returning to rollup.
I initially opened this PR with just a failing test case to confirm the failure in CI before adding the fix.
> fix(typescript): normalize returned module ids

- packages/eslint/src/index.ts
Rename import `rollup-pluginutils` to `@rollup/pluginutils`
> fix(eslint): rename wrong pluginutils import

- packages/dynamic-import-vars/README.md
Typo in the import statement, should be @rollup since it's a scoped package. Fixing this typo will prevent accidental "cannot resolve module" errors ;).
> docs(dynamic-import-vars): fix typo in README.md

- packages/node-resolve/src/index.js
- packages/node-resolve/src/resolveImportSpecifiers.js
- packages/node-resolve/test/fixtures/exports-directory-specificity.js
- packages/node-resolve/test/fixtures/exports-literal-specificity.js
- packages/node-resolve/test/fixtures/node_modules/exports-directory-specificity/foo-one/a.js
- packages/node-resolve/test/fixtures/node_modules/exports-directory-specificity/foo-three/a.js
- packages/node-resolve/test/fixtures/node_modules/exports-directory-specificity/foo-two/a.js
- packages/node-resolve/test/fixtures/node_modules/exports-directory-specificity/package.json
- packages/node-resolve/test/fixtures/node_modules/exports-literal-specificity/exported-foo/a.js
- packages/node-resolve/test/fixtures/node_modules/exports-literal-specificity/foo-a.js
- packages/node-resolve/test/fixtures/node_modules/exports-literal-specificity/package.json
- packages/node-resolve/test/package-entry-points.js
List any relevant issue numbers: https://github.com/rollup/plugins/issues/672
We didn't properly account for specificity when selecting the exports condition. This applies that properly, selecting first a literal match and then iterating the sorted list of keys based on specificity.
This also includes https://github.com/rollup/plugins/pull/669 to avoid two PRs creating merge conflicts.
> fix(node-resolve): export map specificity

- packages/alias/src/index.ts
List any relevant issue numbers: https://github.com/rollup/plugins/issues/679
`entries` is specified as `readonly` here: https://github.com/rollup/plugins/blob/366380eb33c31957fa80dd1df9d4cec8477294c2/packages/alias/types/index.d.ts#L30
This change makes the implementation `readonly` to match the type definition. TypeScript 4 has stricter checks for `readonly` and will eventually require this change.
> alias: add missing readonly to internal function

- packages/typescript/package.json
- packages/typescript/src/tslib.ts
- packages/typescript/src/watchProgram.ts
- pnpm-lock.yaml
I don't expect this would cause folks issues in upgrading. The only code changes I had to make were slight and internal to the plugins, so I don't think the external types will change
There are a number of open issues with the TypeScript plugin. I was poking around to see what would be required to fix some of them. Being on an older version of TypeScript makes things harder. E.g. it seems like there might be a bug in one of the TypeScript methods (https://github.com/rollup/plugins/issues/287#issuecomment-674552597), but I can't report issues to the TypeScript team unless using the latest version of TypeScript. I also was trying to use an API that I saw in `tsc` and appeared to be exported, but VS Code is telling me it doesn't exist …
> Build TypeScript plugin with TypeScript 4

- packages/wasm/src/helper.ts
- packages/wasm/src/index.ts
- packages/wasm/test/test.js
List any relevant issue numbers: #574 
* Remove calls to `eval` which would raise warnings in rollup
* Add a dummy sourcemap to suppress warnings in rollup (See [@rollup/json/index.js#L23](https://github.com/rollup/plugins/blob/8c3a3a6eaa4dc301a4dcd6ea0b4efcc8243c9e12/packages/json/src/index.js#L23))
* Add eslint ignore statements to wasm test files to pass linting
> fix(wasm): Remove `eval` calls and enable dummy sourcemap

- packages/node-resolve/README.md
This was kind of unexpected behavior so I thought it would be useful to document it here.
> Add clarification on the order of package entrypoints

- packages/commonjs/test/types.ts
`lint` fails on `master` for this project:
>packages/commonjs/test/types.ts
3:32  error  'RollupOptions' is not defined  no-undef
> chore(commonjs): fix lint error

- .eslintrc.js
This project runs `eslint --fix` as part of `pnpm -r lint`. There are a lot of files that do not abide by this rule, so it tries to replace every instance of `Object.assign` with a spread operator. There are a pretty good number of places where the code does not conform to these expectations. This would let the code remain how it is instead of it being automatically updated
There's one other major issue to address and I've raised a separate issue for it: https://github.com/rollup/plugins/issues/734
> Turn off lint rule that's causing attempted reformatting

- packages/node-resolve/src/resolveImportSpecifiers.js
- packages/node-resolve/test/fixtures/exports-ts-fallback.ts
- packages/node-resolve/test/fixtures/node_modules/exports-ts-fallback/a.js
- packages/node-resolve/test/fixtures/node_modules/exports-ts-fallback/package.json
- packages/node-resolve/test/package-entry-points.js
When attempting to resolve a list of specifiers we are logging warnings for failed attempts. This change only logs the last failed attempt.
This is visible for example when resolving `.js` imports in a `.ts` file.
> fix(node-resolve): only log last resolve error

- packages/typescript/src/index.ts
- packages/typescript/test/fixtures/incremental-output-cache/main.ts
- packages/typescript/test/fixtures/incremental-output-cache/tsconfig.json
- packages/typescript/test/test.js
~~I'm still trying to figure out why [this test](https://github.com/rollup/plugins/blob/e4a4cec3ef0419f0a9a6ef6a02ef4034c7919451/packages/typescript/test/test.js#L853-L878) didn't fail before this fix.~~
It was because the bundle output wasn't written to disk, so the second run would be identical to the first as TypeScript wouldn't find the existing `.tsbuildinfo`.
List any relevant issue numbers: #681
Fixes #681
The plugin now checks if TypeScript has emitted a tsbuildinfo file. If and only if it has, the plugin emits the tsbuildinfo file.
This prevents the TypeError from occurring when the plugin used to emit …
> fix(typescript): only emit tsbuildinfo file when there is something to emit

- packages/legacy/package.json
- packages/legacy/src/index.js
- packages/legacy/test/test.js
- pnpm-lock.yaml
Vite 2 implements a [universal rollup plugin API](https://vitejs.dev/guide/api-plugin.html) (for the ESM based dev server, and the build using rollup). Plugins are mostly compatible. I am maintaining a [compatibility list for official rollup plugins here](http://vite-rollup-plugins.patak.dev/).
One difference in the dev server is that Vite normalizes paths to use posix slashes (in the same way as normalizePath in @rollup/pluginutils) while resolving ids. This is [not an issue](https://github.com/vitejs/vite/pull/1693) generally because utils like createFilter also normalize ids while matching.
This PR uses rolluputils.normalizePath to normalizes ids in the exports map for @rollup/plugin-legacy so it is compatible with Vite. This will …
> feat(legacy): normalize exports paths

- packages/commonjs/src/ast-utils.js
- packages/commonjs/src/transform-commonjs.js
- packages/commonjs/test/fixtures/samples/shorthand-require/main.js
- packages/commonjs/test/test.js
List any relevant issue numbers: #763
Checks that `require` is shorthand property.
> fix(commonjs): correctly replace shorthand `require`

- packages/typescript/types/index.d.ts
~~If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking.~~
Before, using type definitions from this package without the `skipLibCheck` option for TypeScript would result in type checking errors. We fix this and to ensure that the types stay correct we have the checked as part of the build process by disabling the `skipLibCheck` option.
> fix(typescript): type declarations

- packages/node-resolve/README.md
List any relevant issue numbers: #772
With a recent update the plugin now marks builtins as external automatically when `resolveBuiltins` is not explicitly `false`.
Therefore I think the documentation to use `builtins` to achieve the same behaviour is not needed, given doing it is essentially a no-op.
Also when using `rollup-plugin-node-polyfills` you should set `preferBuiltins ` to `false`, and this was not super clear the way it was worded previously.
> docs(node-resolve): clearer "Resolving Built-Ins" doc

- packages/node-resolve/rollup.config.js
Noticed a warning when building because we were using `url` but not listed it as an external. This does that, and also makes the build fail on a warning so we catch things like this in the future.
> chore(node-resolve): mark `url` as an external and throw on warning

- packages/typescript/test/test.js
List any relevant issue numbers: https://github.com/rollup/plugins/issues/287
I had the assertion wrong. This is now correct. I verified it matches the output of running `tsc` directly.
The test passes with typescript 4.2.0-beta. I didn't upgrade it and enable the test since it's still in beta, but can do that if you prefer
> Fix TypeScript src-dir test

- packages/babel/README.md
- packages/babel/src/index.js
- packages/babel/test/as-input-plugin.js
- packages/babel/types/index.d.ts
~Since `createFilter` has a third options, which can pass `resolutionBase`. It might be better the option can be controlled by `rollup-plugin-babel`~
According to the following discussion, adding filter option to @rollup/plugin-babel.
> feat(babel): add filter option

- packages/html/package.json
List any relevant issue numbers: Fixes #801
When migrating this to typescript, you forgot to update the files array
> Fix plugin-html’s "files" array in package.json

- .circleci/config.yml
- package.json
- packages/alias/package.json
- packages/auto-install/package.json
- packages/data-uri/package.json
- packages/eslint/package.json
- packages/html/package.json
- packages/pluginutils/package.json
- packages/typescript/package.json
- packages/virtual/package.json
- packages/wasm/package.json
- packages/wasm/tsconfig.json
- pnpm-lock.yaml
fixes #779 
Have early feedback in every PR that typescript types are not compromised.
Add task test:ts to every plugin written in typescript
Run  test:ts on circle ci config
> Check types in typescript packages in CI

- packages/replace/test/types.ts
- packages/replace/types/index.d.ts
🤦‍♂️ Failed to add types for change in previous PR (#798). Closes #812.
> fix(replace): add missing types for new `preventAssignment` option

- packages/commonjs/src/transform-commonjs.js
- packages/commonjs/test/fixtures/form/compiled-esm-define-exports-empty/input.js
- packages/commonjs/test/fixtures/form/compiled-esm-define-exports-empty/output.js
resolves #762
Currently if there are no inclusions of commonjs helpers, references to module/exports or dynamic requires - then the transform functions returns without modifying the code.
This PR changes that to consider `isRestorableCompiledEsm`, as this basically means that an ES module was transformed into CJS, and we want to return an ES module.
> fix(commonjs): `isRestorableCompiledEsm` should also trigger code transform

- packages/typescript/README.md
- packages/typescript/package.json
plugn-typescript used an API from typescript [ts.getOutputFileNames](https://github.com/rollup/plugins/blob/1602ecb411704651b020f33287b170a9ee51861a/packages/typescript/src/outputFile.ts#L60), which is introduced by [this commit](https://github.com/microsoft/TypeScript/commit/e430f2a81cafb3fe31a32c42321c769a3d084056) in typescript 3.7 beta.
Encounter `ts.getOutputFileNames is not a function` with ts 3.6.4, after upgrading to ts 3.7, the issue was gone.
> update plugin typescript readme and peerDeps version

- packages/replace/README.md
I discovered this option because it was used in the `preventAssignment` example, but it wasn't documented.
I got the option type from the `.d.ts` file.
> [plugin-replace] Document the `values` option

- packages/node-resolve/src/fs.js
Using the node-resolve plugin in a browser where the fs module is mocked fails to find resolve any paths. Upon debugging this issue, it appears to be because `fs.exists` is passed to `util.promisify`. The Node [docs](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) explicitly call out this function as being non-standard and not following the pattern for `util.promisify` to work correctly.
As far as I can tell, this works on Node because `fs.exists` actually internally already provides a promisified version via: https://nodejs.org/api/util.html#util_custom_promisified_func …
> Fix bug where fs.exists is incorrectly promisified

- packages/run/README.md
- packages/run/src/index.ts
- packages/run/test/test.js
- packages/run/types/index.d.ts
#769 
This PR adds functionality to enable optional manual restarts of the running bundle by entering `rs`, `restart` or pressing <kbd>Ctrl</kbd>+<kbd>K</kbd> on the terminal followed by <kbd>Enter</kbd>. This mimics the behavior of [nodemon](https://github.com/remy/nodemon#manual-restarting). Additionally, the terminal screen can be cleared by entering `cls`, `clear` or pressing <kbd>Ctrl</kbd>+<kbd>L</kbd> followed by <kbd>Enter</kbd>.
The use case for this functionality is developing applications that reference external configuration files, resources or databases that may …
> feat(run): add `allowRestarts` option

- packages/alias/package.json
- packages/auto-install/package.json
- packages/babel/package.json
- packages/beep/package.json
- packages/buble/package.json
- packages/commonjs/package.json
- packages/data-uri/package.json
- packages/dsv/package.json
- packages/dynamic-import-vars/package.json
- packages/eslint/package.json
- packages/graphql/package.json
- packages/html/package.json
- packages/image/package.json
- packages/inject/package.json
- packages/json/package.json
- packages/legacy/package.json
- packages/multi-entry/package.json
- packages/node-resolve/package.json
- packages/pluginutils/package.json
- packages/replace/package.json
- packages/run/package.json
- packages/strip/package.json
- packages/sucrase/package.json
- packages/typescript/package.json
- packages/url/package.json
- packages/virtual/package.json
- packages/wasm/package.json
- packages/yaml/package.json
This is a trivial thing, but every time I search for a Rollup plugin, the top results are npm package listing pages. That's great, but of the two sidebar links, one points to the plugins repo itself, whereas the other points to the package's README. This uses npm's [repository.directory package.json field](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#:~:text=you%20can%20specify%20the%20directory%20in%20which%20it%20lives) to make them both point to the correct location (see [npm cli source](https://github.com/npm/cli/blob/8806015fdd025f73ccf4001472370eafd3c5a856/lib/repo.js#L35-L48) that confirms the logic).
> chore(repo): Add "directory" to package.json repository fields.

- packages/node-resolve/README.md
This has caused a bit of confusion in uuidjs/uuid#544.
List any relevant issue numbers: https://github.com/uuidjs/uuid/issues/544
The documentation could be a bit clearer on how to get the resolution behavior of Node.js. Right now, folks have to deduce that from reading the Node.js documentation alongside the plugin docs.
> docs(node-resolve): Document how to get Node.js exports resolution

- packages/typescript/src/index.ts
List any relevant issue numbers: #860 
ts watch program needs to restart on each build, otherwise the emitted assets won't change, `emittedFiles` will cache the first build all the time
> fix: restart watch program on each build

- packages/dynamic-import-vars/src/dynamic-import-to-glob.js
- packages/dynamic-import-vars/test/src/dynamic-import-to-glob.test.js
Allow dynamically importing files in the same directory with an extra suffix before the extension.
My motivating example is trying to import a library generated with [Stencil](https://stenciljs.com/docs/introduction). It generates a dynamic import that looks like this:
```
return import(
/* webpackInclude: /\.entry\.js$/ */
/* webpackExclude: /\.system\.entry\.js$/ */
/* webpackMode: "lazy" */
`./${bundleId}.entry.js${ ''}`)
```
My interpretation of the [README](https://github.com/rollup/plugins/blob/master/packages/dynamic-import-vars/README.md) suggests this should be possible. …
> fix(dynamic-import-vars): allow ./${var}.suffix.js

- packages/pluginutils/package.json
As I looked into the codebase, I found that `rollup` isn't actually required by the `pluginutils` package. So the peer dependency requirement is extraneous.
This fixes the unexpected package manager warnings that some projects may depend on the `@rollup/pluginutils` module but don't need the full `rollup` dependency. ()
P.S. the `@rollup/plugin-node-resolve` package doesn't need `rollup` for its functionality either (except for the typing support). Should I remove that peer dependency, too?
> fix(pluginutils): remove extraneous peer dependency requirement

- packages/node-resolve/src/index.js
- packages/node-resolve/test/browser.js
- packages/node-resolve/test/fixtures/browser-local-relative.js
- packages/node-resolve/test/fixtures/nested/browser-local-relative.js
- packages/node-resolve/test/fixtures/package.json
List any relevant issue numbers: #919, eemeli/yaml#291
For each entry in a package.json `"browser"` object entry, the `browserMapCache` is filled with mapped paths at keys using both the raw source of the path that needs to be remapped, as well as the resolved path. This effectively enables both package name imports (like `"foo"`) as well as relative path imports (like `"./foo"`) to work when `doResolveId` is called. However, this causes a problem when the raw form of a relative import in a sub-path matches a value that's included in the package.json `"browser"` entry.
In other words, if `"browser"` includes …
> fix(node-resolve): handle browser-mapped paths correctly in nested contexts

- packages/typescript/src/index.ts
- packages/typescript/src/options/plugin.ts
- packages/typescript/src/options/validate.ts
- packages/typescript/src/outputFile.ts
- packages/typescript/test/fixtures/incremental-single/main.ts
- packages/typescript/test/fixtures/incremental-single/tsconfig.json
- packages/typescript/test/test.js
- packages/typescript/types/index.d.ts
Typescript
https://github.com/rollup/plugins/issues/698
After removing the validation, I get an error that rollup should not be emitting files outside of the `outDir` directory.
This seems strange as the typescript incremental cache file is not a user facing file. I removed the usage of rollup's `emitFile` and replaced it with how `TsCache` writes their files, which should be the closest equivalent.
> Fix incremental typescript cache

- packages/alias/src/index.ts
- packages/alias/test/test.js
- pnpm-lock.yaml
We ran into an issue where we had aliases to paths on another Windows drive which was not working. After some investigation, I found out that this is because the drive letter is being removed in the alias plugin. Removing that piece of code made the alias work properly across multiple Windows drives.
Questions:
- I also removed usage of the `slash` library as it's not actually needed to work properly. Do you want me to remove the library entirely?
- The normalize functions are doing nothing more than just returning the `id` and `path` straight away, so they could technically be …
> fix(alias): paths for aliases across multiple Windows drives

- packages/commonjs/src/utils.js
- packages/commonjs/test/fixtures/samples/module-path-separator/foo/index.js
- packages/commonjs/test/fixtures/samples/module-path-separator/main.js
- packages/commonjs/test/test.js
List any relevant issue numbers: #923
When a module whose file name is `index.js` is resolved to a module ID containing a directory separator that is different from [`path.sep`](https://nodejs.org/docs/latest/api/path.html#path_path_sep) of the current platform, the commonjs plugin incorrectly infers the base name of the module. This causes the absolute path of the module to be embedded into the bundle, and prevents generating reproducible builds across different machines.
For example, with a module ID of `C:/Users/Phil/Documents/GitHub/test-vite-app/node_modules/react/index.js` on Windows, the plugin generates …
> fix(commonjs)!: Correctly infer module name for any separator

- packages/image/package.json
Fixes an issue where `tests` are being added to the `files` part of `package.json` for `packages/image`.
Which should fix types by consuming apps etc.
> fix(image): include types, not tests, in package.json files

- packages/node-resolve/README.md
Just noticed the heading depth for the option was wrong when I read it.
> docs(node-resolve): fix readme heading depth

- packages/commonjs/README.md
- packages/commonjs/src/index.js
List any relevant issue numbers: https://github.com/rollup/plugins/issues/1004
There's a warning for this value in the docs saying it should normally be set to `true`, so it seems like the current default of `false` might not be a very good one
> fix(commonjs)!: use safe default value for ignoreTryCatch

- packages/sucrase/src/index.js
- packages/sucrase/test/types.ts
- packages/sucrase/types/index.d.ts
Pull Request Requirements:
* Please include tests to illustrate the problem this PR resolves.
* Please lint your changes by running `npm run lint` before creating a PR. **(I believe the correct command is `pnpm lint`, it failed though before I made changes)**
* Please update the documentation in `/docs` where necessary **(Couldn’t find a “/docs” folder.)**
List any relevant issue numbers: none
The `disableESTransforms` option was added in [Sucrase 3.19.0].
The TypeScript types that ship with `@rollup/plugin-sucrase` says that `disableESTransforms` is a valid option, but supplying it makes no difference.
This …
> fix(sucrase): Pass `disableESTransforms` option and make types match options we support

- packages/html/types/index.d.ts
#974 
When using a `rollup.config.ts` file I am seeing a linting error when using the plugin in the prescribed way (with no arguments). Given the function definition uses a default, I think the type declaration can be amended to list the options argument as optional. This way, people do not get linting errors/have to add a redundant default argument: eg.`html({})`.
EDIT: Added `html` to name and a fixed typo.
> refactor(html): function signature of html updated

- packages/beep/package.json
The typings were not exported for `beep` plugin even though they existed in the package.
> fix(beep): ensure types are exported in npm pkg

- packages/graphql/README.md
- packages/graphql/src/index.js
- packages/graphql/test/fixtures/graphqls/index.js
- packages/graphql/test/fixtures/graphqls/schema.graphqls
- packages/graphql/test/test.js
Closes #1027
This PR adds automatic support for `.graphqls` files, which are used by some tools (gqlgen, spring, maybe others) as schema definition files.  It didn't seem worthwhile to make this user-configurable, but I could if desired.
> feat(graphql): support .graphqls files

- packages/node-resolve/test/fixtures/exports-only-worker-condition-with-browser-field.js
- packages/node-resolve/test/fixtures/exports-worker-condition-with-browser-field.js
- packages/node-resolve/test/fixtures/node_modules/exports-only-worker-condition-with-browser-field/browser-field-entry.js
- packages/node-resolve/test/fixtures/node_modules/exports-only-worker-condition-with-browser-field/package.json
- packages/node-resolve/test/fixtures/node_modules/exports-only-worker-condition-with-browser-field/webworker-condition-entry.js
- packages/node-resolve/test/fixtures/node_modules/exports-worker-condition-with-browser-field/browser-condition-entry.js
- packages/node-resolve/test/fixtures/node_modules/exports-worker-condition-with-browser-field/browser-field-entry.js
- packages/node-resolve/test/fixtures/node_modules/exports-worker-condition-with-browser-field/package.json
- packages/node-resolve/test/fixtures/node_modules/exports-worker-condition-with-browser-field/webworker-condition-entry.js
- packages/node-resolve/test/package-entry-points.js
I was wondering if this would work correctly - I've figured out that the quickest way to found out would be to check the test suite but I couldn't find **any** `exportConditions`-related test. The only place where "exportCondition:" string appears in the codebase is this type test:
https://github.com/rollup/plugins/blob/53776ee3fc59587fe5ff0c756216185f48372507/packages/node-resolve/test/types.ts#L14
Since it felt like such tests are missing, I've decided to just add them 😉
> test(node-resolve): add tests for mixing custom `exportConditions` with `browser: true`

- packages/dynamic-import-vars/package.json
- packages/dynamic-import-vars/src/index.js
- pnpm-lock.yaml
Looks like globby features are not used in this plugin and internal
fast-glob can be used instead. It also has a bit smaller install size.
https://packagephobia.com/result?p=globby
https://packagephobia.com/result?p=fast-glob
Bumped pluginutils too.
> refactor(dynamic-import-vars): replace globby with fast-glob

- packages/inject/index.d.ts
- packages/replace/types/index.d.ts
This PR adds types for the `sourceMap` option which is respected by both plugins but not currently included in the typing.
* replace: https://github.com/rollup/plugins/blob/93cf0a73aa9c386005923fcb45c6cf85d58d4a1b/packages/replace/src/index.js#L106-L108
* inject: https://github.com/rollup/plugins/blob/cfb45553566265b27f82570b717a7f3c8f91eea6/packages/inject/src/index.js#L82
> fix(inject,replace): add types for `sourceMap` option

- packages/node-resolve/src/index.js
- packages/node-resolve/test/test.js
Resolves #1060 
While node-resolve was already calling other resolvers to allow them to mark modules as external, meta-information was ignored so far. This fix will make sure that all meta information added by other plugins is preserved (except moduleSideEffects that is).
> fix(node-resolve): forward meta-information from other plugins

- packages/alias/src/index.ts
- packages/alias/test/test.js
- packages/alias/types/index.d.ts
This PR removes useless functions and avoid resolving customResolver every time handling resolved.
The previous one (#1000 ) contains a bug that was not detected by the tests (https://github.com/rollup/plugins/pull/1000#issuecomment-946898964). This PR fixes the bug and adds a test for it.
/cc @shellscape I'm very sorry for the trouble I caused.
> refactor(alias): avoid resolving customResolver every time handling resolveId

- packages/node-resolve/package.json
- packages/node-resolve/rollup.config.js
Currently, the version embedded as `version` property into the plugin object is always one version behind. This should fix it by running another build immediately before the package is actually published (which happens after the version has been incremented).
> fix(node-resolve): build before publishing for correct version

- packages/typescript/README.md
Fix typescript readme copy/paste mistake.
1. In the `factory` of `type: 'typeChecker'` I do not see a declaration for the variable `program`, which is passed into the `TypeCheckerRequiringTransformerFactory`.
2. `TypeCheckerRequiringTransformerFactory` seems, to me, to _require_ a `TypeChecker`, however is receiving a `Program`.
3. The `factory`'s parameter `typeChecker` is unused.
> docs(typescript): readme copy/paste mistake

- packages/virtual/README.md
I have recently tested the code from the [readme.md of plugin-virtual](https://github.com/rollup/plugins/blob/master/packages/virtual/README.md). I am currently using Rollup version 2.67.0. The correct and updated option for providing an entry point when bundling with Rollup is using [`input`](https://rollupjs.org/guide/en/#input)
Considering the possibility that this documentation was created during an earlier version of Rollup, I am open to any corrections if necessary.
I have forked this repository and made the necessary change. This will clear the confusion instated with the …
> docs(virtual): Replace 'entry' with 'input' in readme

- packages/babel/src/preflightCheck.js
What it says on the tin - fixes #1089
> fix(babel): consider path delimeter on windows (#1089)

- packages/typescript/README.md
- packages/typescript/src/options/plugin.ts
- packages/typescript/test/test.js
- packages/typescript/types/index.d.ts
Allow explicitly setting compiler options instead of using rest syntax. This is less confusing in documentation and rollup config. It is also less fragile.
An alternative (see rollup-plugin-typescript2) would be to pull all tsconfig overrides out.
```js
{
...
tsconfigOverrides: {
compilerOptions: {},
include: [...]
}
}
```
> fix(typescript): allow explicity compilerOptions

- packages/pluginutils/src/dataToEsm.ts
- packages/pluginutils/test/dataToEsm.ts
|data|oldEsm|newEsm|
|---|---|---|
|`bigint`|`undefined`|`bigint`|
|`Symbol.for()`|`undefined`|`Symbol.for()`|
> feat(pluginutils): support bigint and symbol in dataToEsm

- packages/eslint/types/index.d.ts
ESLint plugin, `exclude` and `include` got a wrong type define. See the screenshot for details, we must cast regex to string for omit the error.
Actually, those options will pass to [`createFilter` function](https://github.com/rollup/plugins/blob/5363f55aa1933b6c650832b08d6a54cb9ea64539/packages/eslint/src/index.ts#L37), so its typing should follow this function's parameters typing.
https://github.com/rollup/plugins/blob/5363f55aa1933b6c650832b08d6a54cb9ea64539/packages/eslint/src/index.ts#L37
> fix(eslint): include and exclude options typing allow to be a regex

- packages/pluginutils/src/createFilter.ts
- packages/pluginutils/test/createFilter.ts
Discovered in https://github.com/rollup/plugins/pull/1144
`createFilter` function is not normalizing paths correctly. Everything is expected to be converted to `/` while on windows it may not be the case as it depends on users input.
> fix(pluginutils): fix path normalisation for createFilter

- packages/typescript/src/tscache.ts
As in several other places in this code base the regex for matching windows drive letters should be `/^([a-zA-Z]+):/` but one case was missing in the implementation of TSCache.
> fix(typescript): Drive letter casing on win32 platforms

- packages/commonjs/src/index.js
- packages/commonjs/types/index.d.ts
Fix https://github.com/rollup/plugins/issues/1046 with configration like
```ts
commonjs({
defaultIsModuleExports: (id: string) => {
if (/react-datetime/.exec(id)) {
return false
}
return "auto"
},
})
```
> feat(commonjs): make defaultIsModuleExports as funtion to config defaultIsModuleExports for each source

- .github/ISSUE_TEMPLATE/BUG.md
All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Replace the `git.io` link with its actual URL.
> chore(repo): replace `git.io` in the issue template

- packages/wasm/README.md
- packages/wasm/src/helper.ts
- packages/wasm/src/index.ts
- packages/wasm/test/test.js
- packages/wasm/types/index.d.ts
Closes #1129
Currently the Wasm rollup plugin emits code that includes calls to
require builtin node modules (`fs` and `path`) as well as builtin
`fetch` in browser environments.
Even though there is an check before the environment specific code is
executed, the mere presence of `require` for builtin node modules will
cause downstream bundlers like `esbuild` and `webpack` to emit errors
when they statically analyze the output.
This commit adds in a `targetEnv` that configures what code is emitted
to instantiate the Wasm (both inline and separate)
- `"auto"` will determine the environment at runtime and invoke the …
> feat(wasm): Add target environment configuration

- packages/wasm/test/fixtures/async.js
The "target environment browser" test invoked the bundled output, which
leads to an undefined error on node 14 as [`atob` was introduced in node
16][0].
This commit uses the same atob polyfill that was introduced in #334
[0]: https://developer.mozilla.org/en-US/docs/Web/API/atob#browser_compatibility
Addresses the release github action breakage as reported in #1132
> fix(wasm): Reference atob polyfill in browser wasm test

- .github/workflows/node-windows.yml
- .github/workflows/release.yml
- .github/workflows/validate.yml
- packages/node-resolve/src/index.js
- packages/node-resolve/test/test.js
Solves an issue mentioned in https://github.com/rollup/plugins/issues/1169#issuecomment-1114070764
Currently, node-resolve is very eager to take over resolution meaning that any resolver placed after the node-resolve plugin may at most resolve ids starting with `\0`. That is mostly fine except when plugins really want to do some proxying as mentioned later in rollup/plugins#1169.
This modifies the logic so that when node-resolve "re-resolves" the resolved id, it not only checks if a plugin marks the id as external, but also checks if a plugin would change the id. That is something …
> fix(node-resolve): Respect if other plugins resolve the resolution to a different id

- packages/node-resolve/package.json
- packages/node-resolve/src/index.js
- packages/node-resolve/test/fixtures/node-protocol.js
- packages/node-resolve/test/prefer-builtins.js
- pnpm-lock.yaml
#1120
Imports with the [`node:` protocol](https://nodejs.org/api/esm.html#node-imports) are currently undetected by this plugin.
Switch to using [is-builtin-module](https://github.com/sindresorhus/is-builtin-module), which handles this protocol and also submodule imports like `fs/promises`.  Functionality is otherwise identical.
I confirmed the added test fails without the other changes in this PR.
> fix(node-resolve): support `node:` protocol

- packages/sucrase/package.json
- packages/sucrase/types/index.d.ts
When typechecking a TS project importing this plugin with `skipLibCheck: false`, a type error is thrown:
```
.yarn/__virtual__/@rollup-plugin-sucrase-virtual-7e2c8dc7a4/0/cache/@rollup-plugin-sucrase-npm-4.0.3-5d2d589
3b4-0f8a729c1b.zip/node_modules/@rollup/plugin-sucrase/types/index.d.ts:3:43 - error TS7016: Could not find 
a declaration file for module 'sucrase/dist/Options'. '/Users/.../.yarn/cache/sucrase-npm-3.21.0-78b7f0f024-
d686f255af.zip/node_modules/sucrase/dist/Options.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/sucrase` if it exists or add a new …
```
> fix(sucrase): use bare specifier to obtain SucraseOptions type

- packages/typescript/package.json
Testing this would be akin to testing npm.
List any relevant issue numbers: 
- #265 
`tslib` is an optional dependency and in a large set of projects goes completely unused (notably anything compiling with babel or which does not require use of the helpers).
Historically, `yarn` and `npm` would warn for peerDependencies but not error, but as better package managers have fixed this mistake (most notably `pnpm`) and worked their way into being industry defaults this behavior has shifted from minor-nuisance to build-breaking.
This PR uses the spec `peerDependencyMeta` respected by both `npm` and `pnpm` to declare …
> fix(typescript): allow tslib peerDependency to be optional for npm and pnpm

- packages/typescript/README.md
- packages/typescript/src/index.ts
- packages/typescript/test/test.js
Previously, type declaration files were only emitted if `outputOptions.dir` was
used and not `outputOptions.file` or, as a side effect, if the tsconfig file was
specified via a qualified path. This commit fixes that, such that types are
also emitted for single file builds.
> fix(typescript): fix declaration file generation for single file outputs

- packages/dynamic-import-vars/src/dynamic-import-to-glob.js
- packages/dynamic-import-vars/test/src/dynamic-import-to-glob.test.js
Currently the plugin will fail my build when I import something like: 
```
import(`https://some.cdn.com/package/${version}/index.js`);
```
Since this import is 'external', and doesn't need to look on the filesystem, these kind of imports should be allowed to pass through and go untouched by the plugin.
> fix: exclude external imports

- packages/node-resolve/src/index.js
- packages/node-resolve/test/fixtures/cyclic-commonjs/main.js
- packages/node-resolve/test/fixtures/cyclic-commonjs/other.js
- packages/node-resolve/test/test.js
- resolves #1258 
It turns out in the change that lead to node-resolve 14, I forgot to forward node-resolves own "isRequire" flag in its call to "this.resolve", sending the commonjs plugin into a deadlock. Would like to merge this tomorrow if there are no concerns as it is an important hot fix.
> fix(node-resolve): handle circular commonjs

- packages/babel/README.md
- packages/babel/types/index.d.ts
- packages/buble/README.md
- packages/buble/types/index.d.ts
- packages/commonjs/README.md
- packages/commonjs/types/index.d.ts
- packages/dsv/types/index.d.ts
- packages/dynamic-import-vars/types/index.d.ts
- packages/graphql/README.md
- packages/image/README.md
- packages/image/types/index.d.ts
- packages/inject/README.md
- packages/inject/index.d.ts
- packages/replace/README.md
- packages/replace/types/index.d.ts
- packages/strip/types/index.d.ts
- packages/sucrase/README.md
- packages/sucrase/types/index.d.ts
- packages/typescript/README.md
- packages/url/README.md
- packages/url/types/index.d.ts
- packages/yaml/README.md
- packages/yaml/types/index.d.ts
`createFilter` func from `@rollup/pluginutils` <=v3.0.10 uses picomatch and >v3.0.10 uses `minimatch` (https://github.com/rollup/plugins/pull/306). 
[`picomatch` supports slightly different features from `minimatch`](https://github.com/micromatch/picomatch#library-comparisons). https://github.com/rollup/plugins/tree/master/packages/pluginutils#include-and-exclude
So I updated documents/dts from "minimatch pattern" to "picomatch pattern".
This is the list that shows which plugin uses which version of `@rollup/pluginutils`:
- `@rollup/plugin-babel`: ^3.1.0
- `@rollup/plugin-buble`: …
> chore(repo): correct READMEs, minimatch to picomatch

- packages/pluginutils/README.md
- packages/pluginutils/package.json
- packages/pluginutils/rollup.config.mjs
- packages/pluginutils/src/addExtension.ts
- packages/pluginutils/src/attachScopes.ts
- packages/pluginutils/src/createFilter.ts
- packages/pluginutils/src/dataToEsm.ts
- packages/pluginutils/src/extractAssignedNames.ts
- packages/pluginutils/src/makeLegalIdentifier.ts
- packages/pluginutils/src/normalizePath.ts
- packages/pluginutils/test/attachScopes.ts
- packages/pluginutils/types/index.d.ts
- pnpm-lock.yaml
BREAKING CHANGES: Requires Node 14
If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking.
This PR updates the plugin for Rollup 3 compatibility. This will not change compatibility with older Rollup versions.
* It should be merged after #1277
It contains the following:
* Update minimal required Node version to 14 (also reflected in README, breaking change)
* Extend Rollup peerDependency version with `||^3.0.0`
* Make Rollup an optional peerDependency as technically, plugins do not require Rollup but only depend on its API. Apparently solves issues with pnpm, see #1272
* Use a shared Rollup config for all plugins
* This allows to share …
> fix(pluginutils): prepare for Rollup 3

- packages/pluginutils/package.json
- pnpm-lock.yaml
List any relevant issue numbers: #1315
estree types are required for downstream packages, since pluginutils/types/index.d.ts makes use of them.
They were previously already part of `dependencies` (vs. `devDependencies`, where they currently are) but were accidentally moved in #616. This breaks TypeScript projects on the newest versions of `@rollup/plugin-typescript`, for example. See #1315 for more info and a reproduction.
> fix(pluginutils): Move `@types/estree` to dependencies (fixes #1315)

- packages/alias/package.json
- packages/auto-install/package.json
- packages/babel/package.json
- packages/beep/package.json
- packages/buble/package.json
- packages/data-uri/package.json
- packages/dsv/package.json
- packages/dynamic-import-vars/package.json
- packages/eslint/package.json
- packages/graphql/package.json
- packages/html/package.json
- packages/image/package.json
- packages/inject/package.json
- packages/json/package.json
- packages/legacy/package.json
- packages/multi-entry/package.json
- packages/node-resolve/package.json
- packages/pluginutils/package.json
- packages/replace/package.json
- packages/run/package.json
- packages/strip/package.json
- packages/sucrase/package.json
- packages/typescript/package.json
- packages/url/package.json
- packages/virtual/package.json
- packages/wasm/package.json
- packages/yaml/package.json
- pnpm-lock.yaml
This adds a small unimportant change to all dependencies to hopefully trigger automatic releases.
> fix(repo): trigger releases

- packages/babel/README.md
> docs(babel): small typo in babel plugin readme

- packages/json/README.md
plugin-json now uses pluginutils@^5.0.1 that uses `picomatch` instead of `minimatch` (previously: ^3.0.8).
I updated document from "minimatch pattern" to "picomatch pattern". Since they have a slightly different behavior.
Related: #1260
> docs(json): correct minimatch to picomatch

- packages/typescript/src/index.ts
- packages/typescript/test/test.js
- #1230
The commit 5f78173 changed the behaviour of the typescript plugin. This introduced the issue #1230: The `declarationDir` was now ignored for single file setups. I made some analysis and found the problem:
* In the construction of the plugin the typescript configuration is parsed
* while parsing all paths are made absolute, prepended with `process.cwd()` ([packages/typescript/src/options/tsconfig.ts#L147](https://github.com/rollup/plugins/blob/master/packages/typescript/src/options/tsconfig.ts#L147))
* in order to output declaration files the `baseDir` is determied from the …
> fix(typescript)!: incorrect declarations directory

- packages/typescript/src/index.ts
- packages/typescript/test/fixtures/incremental-watch-off/dist/.tsbuildinfo
- packages/typescript/test/fixtures/incremental-watch-off/main.ts
- packages/typescript/test/fixtures/incremental-watch-off/original.txt
- packages/typescript/test/fixtures/incremental-watch-off/tsconfig.json
- packages/typescript/test/test.js
…up when watchMode is false
resolves #1354 - Typescript plugin doesn't emit latest assets on rollup when watchMode is false
When watchMode is false the TS Compiler watch program is closed when the build ends. However, if another build starts, using the same plugin instance, a new program wasn't created.
> fix(typescript): emit assets when `watchMode` is false. fixes #1354

- packages/commonjs/package.json
- packages/dynamic-import-vars/package.json
- packages/inject/package.json
- packages/replace/package.json
- packages/strip/package.json
- pnpm-lock.yaml
List any relevant issue numbers: fixes #1365
`sourcemap-codec@1.4.8` was deprecated and installing these plugins shows the following warning.
> npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
This PR updates `magic-string` to `^0.27.0` to remove that warning.
`magic-string@0.27.0` does not include any breaking changes.
https://github.com/Rich-Harris/magic-string/blob/master/CHANGELOG.md
> fix(commonjs,dynamic-import-vars,inject,replace,strip): update magic-string

- packages/json/src/index.js
- packages/json/test/test.js
Previously, when JSON failed to parse (say it was transformed by another plugin), you would get a message like below. The json plugin fails to parse, and, because the error message doesn't match the `/[\d]/` regex, you get an uninformative warning message. Even if the regex *did* match, it would only match the first digit, not the whole line number.
```
bundles test/bench/versions/benchmarks.ts, src/source/worker.ts → rollup/build/benchmarks/versions...
[!] (plugin json) TypeError: Cannot read properties of null (reading '0')
src/style-spec/reference/v8.json
TypeError: Cannot read …
```
> fix(json)!: log more robustly when JSON parsing fails

- packages/wasm/src/helper.ts
- packages/wasm/test/test.mjs
When node.js is reading the wasm file and encounters an error (like if the file doesn't exist or user doesn't have permissions to read). It will still try and call `_instantiateOrCompile` with `undefined`, which results in an uncaught exception, possibly obscuring the error. As instead of the file read error, the following error will return:
> TypeError: WebAssembly.compile(): Argument 0 must be a buffer source
This can be replicated with the following script (don't execute at a REPL):
```js
(async () => {
await new Promise((resolve, reject) => {
reject(new Error("permission error"));
resolve(WebAssembly.compile(undefined));
});
})();
```
Node.js will exit with an error code and print only the type error to stderr.
If we try and …
> fix(wasm): rejecting with error on node.js file read

- .github/ISSUE_TEMPLATE/BUG.md
The current repl.it template no longer works with Rollup 3 because it runs on Node 14. For Rollup core, I created a minimal StackBlitz template that we could also use for plugins if we want to. Or we fork it to have a dedicated one for plugins.
I also removed the Rollup REPL as reproduction option because, well, the REPL does not support plugins, so it is probably not helpful here.
> chore(repo): Add StackBlitz reproduction template

- CODEOWNERS
- packages/terser/src/module.ts
- packages/terser/tsconfig.json
fixes https://github.com/rollup/plugins/issues/1366
> fix(terser): __filename not defined

- packages/terser/src/module.ts
- packages/terser/src/type.ts
- packages/terser/src/worker.ts
- packages/terser/test/test.js
> feat(terser): emit source map

- packages/typescript/src/index.ts
- packages/typescript/test/test.js
#1267 
BREAKING CHANGES: The signature of the error being thrown has changed.
This should fix the issue #1267, which is caused by the use of `order: "post"` as part of https://github.com/rollup/plugins/pull/1245. It will prevent the typescript plugin from resolving files which are not included by its provided configuration/options. Instead the `node-resolve` plugin will again handle these cases, which is able to correctly handle the `browser` config parameter. The same fix has been done for the `rollup-plugin-typescrip2` here: …
> fix(typescript)!: don't resolve filtered files (#1267)

- packages/eslint/README.md
- packages/eslint/package.json
- packages/eslint/src/index.ts
- packages/eslint/test/test.mjs
- packages/eslint/test/types.ts
- packages/eslint/types/index.d.ts
1. ESLint's [`CLIEngine` class has been deprecated](https://eslint.org/docs/latest/user-guide/migrating-to-7.0.0#-the-cliengine-class-has-been-deprecated), so the latest `@types/eslint` 8.x no longer exports the `CLIEngine` type, so the latest version of `@rollup/plugin-eslint` formatter is inferred to have the wrong argument type.
2. The latest type of `ESLint.Formatter` allows to return async values, while the current `@rollup/plugin-eslint` only supports sync function.
- [Change Request: Support async formatter](https://github.com/eslint/eslint/issues/15242)
- [feat: support async formatters](https://github.com/eslint/eslint/commit/f1b7499a5162d3be918328ce496eb80692353a5a)
> fix(eslint): fix async support for `formatter` option and TypeScript types

- packages/alias/package.json
- packages/auto-install/package.json
- packages/buble/package.json
- packages/commonjs/package.json
- packages/data-uri/package.json
- packages/dsv/package.json
- packages/dynamic-import-vars/package.json
- packages/eslint/package.json
- packages/graphql/package.json
- packages/html/package.json
- packages/image/package.json
`types` must come first. See the TypeScript docs here: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
> fix(alias,auto-install,buble,commonjs,data-uri,dsv,dynamic-import-vars,eslint,graphql,html,image): types should come first in exports

- packages/terser/src/constants.ts
- packages/terser/src/module.ts
- packages/terser/src/type.ts
- packages/terser/src/worker-pool.ts
- packages/terser/src/worker.ts
- packages/terser/test/test.js
List any relevant issue numbers: https://github.com/rollup/plugins/pull/1341#pullrequestreview-1176576290
The existing WorkerPool creates a new Worker instance for every chunk. This PR reuses them instead. There is still a max number of workers, and the pool size still increases based on demand up to this max.
In my testing, on a 10 CPU machine, this reduced the build time from about 4.5 minutes to 2.5 minutes. This is for a large project with about 8,000 chunks.
I refactored the WorkerPool based on [this](https://nodejs.org/dist/latest-v18.x/docs/api/async_context.html#using-asyncresource-for-a-worker-thread-pool …
> feat(terser): Update WorkerPool to reuse Workers

- CODEOWNERS
- README.md
- packages/swc/README.md
- packages/swc/package.json
- packages/swc/rollup.config.mjs
- packages/swc/src/index.ts
- packages/swc/src/module.ts
- packages/swc/src/type.ts
- packages/swc/test/fixtures/export-default.js
- packages/swc/test/fixtures/export.js
- packages/swc/test/fixtures/test.ts
- packages/swc/test/fixtures/unminified.js
- packages/swc/test/test.js
- packages/swc/test/types.ts
- packages/swc/tsconfig.json
- packages/swc/types/index.d.ts
- pnpm-lock.yaml
https://github.com/rollup/plugins/issues/1413
> feat(swc): initial release

- packages/alias/src/index.ts
- packages/alias/test/test.mjs
If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. - Added
fix #1190
When the Rollup input is passed an aliased path, the `alias` plugin doesn't resolve it because it skips if there's no `importer`. I tracked this behaviour, and found it was not done in the past due to https://github.com/rollup/rollup-plugin-alias/pull/29, but since the internals changed now, that PR's issue isn't relevant and we can continue to alias entry paths now.
> feat(alias)!: resolve entry id

- packages/typescript/README.md
- packages/typescript/package.json
- packages/typescript/src/index.ts
- packages/typescript/test/test.js
- pnpm-lock.yaml
- util/test.d.ts
- util/test.js
* #1049 (even if closed the issue was not resolved until now)
* #1253 (if `output.file` is used, if `output.dir` is used everything should, as it does, be placed inside that directory)
If you configure rollup with `output.file = 'dist/main.js'` and typscript with `'declarationDir: "dist"`
Instead of writing the declarations into `dist/` they  are written into `dist/dist`, and the workaround from the README does not work anymore, if you set 'declarationDir: "."` no declarations are written at all.
So this is fixes by only enforcing declarations inside `output.dir` but not inside …
> feat(typescript): write declaration files in configured directory for `output.file`

- packages/terser/types/index.d.ts
> fix(terser): expose extended terser options interface

- packages/commonjs/src/index.js
- packages/commonjs/test/helpers/util.js
- packages/commonjs/test/test.js
When using the `dynamicRequireTargets` option, the files detected by the option are matched against the dynamic require root path used by the plugin — either the project root or the `dynamicRequireRoot` option to ensure that the root contains all dynamically required paths.
The test is done in `packages/commonjs/index.js:142` through a simple string comparison using `id.indexOf(dynamicRequireRoot)`.
In some cases, it happens that `dynamicRequireRoot` is using the OS path syntax (e.g. backslashes on Windows) but `id` is using unix paths (regular slashes). This leads to an issue where even if the root is correct, a simple string comparison fails to recognise that.
I reused the `normalizePathSlashes()` function provided in the plugin’s …
> fix(commonjs): dynamic require root check was broken in some cases

- packages/terser/src/constants.ts
- packages/terser/src/worker-pool.ts
- packages/terser/src/worker.ts
Fixes issue shown at https://github.com/dumbmatter/rollup-terser-worker-threads by making sure the worker code is only executed when the worker was created by the worker pool.
List any relevant issue numbers: #1482
Currently the worker only checks if it's not running on the main thread and then assumes that if it it isn't, it was created by the worker pool. This isn't true when Rollup itself is being run in a worker.
> fix(terser): don't assume code is running in worker created by the worker pool

- packages/node-resolve/src/index.js
- packages/node-resolve/test/fixtures/ts-import-cjs-extension/import-ts-with-cjs-extension.ts
- packages/node-resolve/test/fixtures/ts-import-cjs-extension/main.cts
- packages/node-resolve/test/fixtures/ts-import-mjs-extension/import-ts-with-mjs-extension.ts
- packages/node-resolve/test/fixtures/ts-import-mjs-extension/main.mts
- packages/node-resolve/test/fixtures/tsx-import-js-extension/MyComponent.tsx
- packages/node-resolve/test/fixtures/tsx-import-js-extension/import-tsx-with-js-extension.ts
- packages/node-resolve/test/fixtures/tsx-import-jsx-extension/MyComponent.tsx
- packages/node-resolve/test/fixtures/tsx-import-jsx-extension/import-tsx-with-jsx-extension.ts
- packages/node-resolve/test/test.mjs
List any relevant issue numbers: #1465
This patch is a combination of PRs #1475 and #1454. It updates the logic for importing from within a TypeScript file. In that case, `.js` can now resolve to `.ts` and `.tsx`, `.jsx` can resolve to `.tsx`, `.mjs` can resolve to `.mts`, and `.cjs` can resolve to `.cts`. This behavior was verified to mimic that of `tsc` itself. Importing from within plain JS files is untouched (e.g., a `.js` import from within a `.js` file will not resolve to `.ts`).
> feat(node-resolve): Resolve js/jsx/mjs/cjs imports from TypeScript files

- packages/commonjs/src/index.js
- packages/commonjs/test/test.js
related #1461
resolves #1507 
This PR primary fix that the test failed in windows, see this action  https://github.com/rollup/plugins/actions/runs/5104720044/jobs/9175831630?pr=1507 from #1507. By the way, I also change  `dynamicRequireRoot` to `normalizedDynamicRequireRoot` for unifying all the path value is normalized, but that also make a break change.
> fix(commonjs): change dynamicRequireRoot to normalizedDynamicRequireRoot && tweak related tests

- packages/yaml/test/types.ts
- packages/yaml/types/index.d.ts
Follow up to #1445.
Follow up to #1445.
Fixes:
> fix(yaml): Add extensions?: string[] to RollupYamlOptions

- packages/pluginutils/src/createFilter.ts
- packages/pluginutils/test/createFilter.ts
relevant: #1538
Currently, if we use a format like `*.js` in the `include` option of `@rollup/plugins`, the plugin cannot filter files correctly, I created a minimal reprodution https://stackblitz.com/edit/rollup-repro-dnz5kc?file=rollup.config.js. This PR addresses this problem with the solution described in issue [#1538](https://github.com/rollup/plugins/issues/1538#issue-1809790595).
> fix(pluginutils): add current working dirctory when pattern starts with one *

- packages/pluginutils/README.md
The [`dataToEsm` API options example](https://github.com/rollup/plugins/tree/master/packages/pluginutils#usage-2) in the documentation is inconsistent with the output:
```ts
import { dataToEsm } from '@rollup/pluginutils';
const esModuleSource = dataToEsm(
{
custom: 'data',
to: ['treeshake']
},
{
compact: false,
indent: '\t',
preferConst: false,
objectShorthand: false,
namedExports: true
}
);
/*
Outputs the string ES module source:
export const custom = 'data';
export const to = ['treeshake'];
export default { custom, to };
*/
```
The right options should be:
```ts
const esModuleSource = dataToEsm(
{
custom: 'data',
to: ['treeshake']
},
{
compact: false,
indent: '\t',
preferConst: true,
objectShorthand: true,
namedExports: true
}
); …
```
> docs(pluginutils): configure the correct options

- packages/babel/package.json
- packages/data-uri/package.json
- packages/dynamic-import-vars/package.json
- packages/html/package.json
- packages/strip/package.json
List any relevant issue numbers: None
This PR adds the missing `prepare` script to several packages, so that they will be built upon running `pnpm install`. This aligns with the behavior of other packages.
Alternatively, this could be solved by having a single `prepare` script in the root package, which can then run this command for all projects in the workspace. This approach would prevent accidental inconsistencies from being introduced, such as those mitigated in this PR. It would also remove duplicated code between package scripts.
Please do let me know what the preferred solution for this would be, and I …
> chore(repo): add missing `prepare` script for several packages

- packages/swc/README.md
- packages/swc/package.json
- packages/swc/src/module.ts
- packages/swc/src/type.ts
- pnpm-lock.yaml
fixes https://github.com/rollup/plugins/discussions/1565
> feat(swc): allow input files to be filtered

- .github/PULL_REQUEST_TEMPLATE.md
I found some PRs that didn't use [`resolves` or other fields](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link the issues it will fix, so I added some tips from https://github.com/rollup/rollup/blob/master/.github/PULL_REQUEST_TEMPLATE.md
> chore(repo): add tips for issue numbers in pr template

- packages/wasm/README.md
- packages/wasm/package.json
- packages/wasm/src/index.ts
- packages/wasm/types/index.d.ts
- pnpm-lock.yaml
The mainly include/exclude handle code is from `@rollup/pluginutils` like the other plugin does, It's already been tested yet.
`@rollup/plugin-wasm` missed the common include/exclude options, this PR added this part.
> feat(wasm): include/exclude options

- packages/dsv/test/types.ts
- packages/dsv/types/index.d.ts
- packages/typescript/src/index.ts
- packages/typescript/src/outputFile.ts
- packages/typescript/test/test.js
List any relevant issue numbers: #1492
(successor to #1493)
This fixes the type definition for the processRow option to the DSV plugin, so that:
- a function that doesn't return anything can be used
- a function that returns a row object that includes non-string values (such as `number` or `Date`) can be used
This PR also removes `undefined` from the return value type, since there is no case where `undefined` is explicitly returned.
> fix(dsv): fix type of processRow option

- packages/commonjs/src/index.js
- packages/commonjs/src/proxies.js
- packages/commonjs/src/transform-commonjs.js
- packages/commonjs/test/fixtures/samples/shebang/main.js
- packages/commonjs/test/test.js
> fix(commonjs): Keep the shebang at the top of the file content

- packages/swc/src/module.ts
- packages/swc/test/test.js
> feat(swc): allow passing `env` property as option

- packages/dynamic-import-vars/src/dynamic-import-to-glob.js
- packages/dynamic-import-vars/test/src/dynamic-import-to-glob.test.mjs
refs https://github.com/vitejs/vite/issues/11824
`dynamicImportToGlob(parse('import(`./${foo}/(foo).js`)'))` returned `./*/(foo).js`. But because `(` has a meaning in glob syntax, it meant a different thing. This PR add a escape process to handle special characters like these.
> fix(dynamic-import-vars): escape special glob characters

- packages/alias/src/index.ts
- packages/alias/test/fixtures/folder/warn-importee.js
- packages/alias/test/fixtures/warn.js
- packages/alias/test/test.mjs
resolves https://github.com/rollup/rollup/issues/5250
When the alias plugin is configured like this
```js
// rollup.config.js
alias({ entries: { $: 'src' } })
```
and there a file like
```js
import { test as test1 } from './sub.js';
import { test as test2 } from '$/sub.js';
console.log(test1);
console.log(test2);
```
https://stackblitz.com/edit/rollup-repro-s5tmli?file=src%2Fmain.js
then, `import './sub.js'` and `import '$/sub.js'` resolves to different module. (The same file is included in the bundle twice.)
I believe this is not what people expect. Also IMO the fact that …
> feat(alias): add warning to avoid unintended duplicate modules

- packages/dynamic-import-vars/README.md
- packages/dynamic-import-vars/src/index.js
- packages/dynamic-import-vars/test/rollup-plugin-dynamic-import-vars.test.js
List any relevant issue numbers: https://github.com/rollup/plugins/pull/1611
This PR allows the "no files found" error introduced in https://github.com/rollup/plugins/pull/1611 to be emitted as a warning using the existing `warnOnError` option.
> fix(dynamic-import-vars): Allow a "no files found" error to be emitted as warning

- packages/pluginutils/README.md
- packages/pluginutils/src/dataToEsm.ts
- packages/pluginutils/test/dataToEsm.ts
- packages/pluginutils/types/index.d.ts
resolves https://github.com/rollup/plugins/issues/1437
This PR adds `namedExports: 'include-arbitrary-name'` option to `dataToEsm` function in `pluginutils`.
When this option is set, `dataToEsm` will generate named export for keys that was not a valid identifier by leveraging Arbitrary module namespace identifier names feature (https://github.com/tc39/ecma262/pull/2154).
> feat(pluginutils): add `includeArbitraryNames: true` to `dataToEsm`

- packages/inject/src/index.js
- packages/pluginutils/README.md
- packages/typescript/README.md
- packages/virtual/package.json
This PR update some legacy plugins names that were left behind.
> chore(repo): consistent plugin names in docs

- .husky/pre-commit
This PR doesn't contain any changes to rollup plugins.
This PR uses `pnpm exec lint-staged` to replace `pnpm dlx lint-staged`. Because lint-staged is installed in monorepo workspace as a dev dependency, it's better to use `pnpm exec`.
> chore(repo): use `pnpm exec` to speed up husky hook

- packages/virtual/src/index.ts
Might fix builds for PR #1578, so it probably could be accepted too then
The "virtual" plugin package currently [imports its own types from `../`](https://github.com/rollup/plugins/blob/9e7f576f33e26d65e9f2221d248a2e000923e03f/packages/virtual/src/index.ts#L5), even though its types are actually placed inside `../types`. Every other plugin appears to correctly import from `../types` too (see e.g. [alias](https://github.com/rollup/plugins/blob/9e7f576f33e26d65e9f2221d248a2e000923e03f/packages/alias/src/index.ts#L5), [auto-install](https://github.com/rollup/plugins/blob/9e7f576f33e26d65e9f2221d248a2e000923e03f/packages/auto-install/src/index.ts#L9), ...).
I stumbled across this while attempting to build …
> chore(repo): fix incorrect import path in virtual plugin

- packages/esm-shim/types/index.d.ts
There's a `provideCJSSyntax` method exported from es-shim plugin but it's not typed, adding the method type to esm-shim plugin's type file
> fix(esm-shim): missing exports in types

- packages/replace/README.md
resolves #1697 
Documentation missing for `sourceMap` inclusion, fixed by adding the option as documented in #1697
> fix(replace): add missing sourceMap documentation

- packages/commonjs/package.json
- packages/commonjs/src/dynamic-modules.js
- pnpm-lock.yaml
List any relevant issue numbers:   resolves #1691 
BREAKING CHANGES: Requires Node.js version >=16.0.0 or >= 14.17, this is the same as glob's need.
both `glob` and `shx` have `inflight` in their deps, so this PR bumps `glob` to the latest and removes `shx`, since it's not been used.
> chore(commonjs)!: bump glob's version

- packages/alias/package.json
- pnpm-lock.yaml
n/a
The `slash` dependency doesn't seem to be used anymore since https://github.com/rollup/plugins/pull/896 where it removed using `slash`.
> fix(alias): remove unused slash dependency

- packages/pluginutils/src/attachScopes.ts
- packages/pluginutils/src/dataToEsm.ts
n/a
Refactors some regex to use non-capturing groups (as captured groups are a little slower), and use `regexp.prototype.exec` instead of `string.prototype.match` for perf.
For the former change, it's hard to use an online tool to measure as the difference is quite small, but here's a local file you can copy using `tinybench` that you can run:
<details>
<summary>File</summary>
```js
import { Bench } from 'tinybench'
const b = new Bench({ iterations: 1000 })
const choices = ['FunctionDeclaration', 'ClassDeclaration', 'VariableDeclaration', 'Identifier']
const strs = Array.from({ …
```
> fix(pluginutils): improve regex performance

- packages/graphql/src/toESModules.js
- packages/graphql/test/fixtures/fragments-with-special-characters/(parentheses)/fragment.graphql
- packages/graphql/test/fixtures/fragments-with-special-characters/[brackets]/fragment.graphql
- packages/graphql/test/fixtures/fragments-with-special-characters/index.js
- packages/graphql/test/fixtures/fragments-with-special-characters/query.graphql
- packages/graphql/test/test.js
If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking.
N/A
This PR fixes an issue in the GraphQL plugin where parentheses in file paths are not properly replaced with a fragment's variable, leading to a parsing error.
The fix works by updating the require statement replacement regex from `/require\(([^)]+)\)/gi` to `/require\(["']([^"']+)["']\)/gi`. The original regex considered a closing parenthesis as the terminator of a require statement, when in fact, we should be looking at a quote character before a parentheses as the terminator. In addition, by excluding the leading and trailing quote from the regex capture group, we can remove …
> fix(graphql): handle parentheses in fragment import file paths.

- packages/node-resolve/package.json
- packages/node-resolve/src/index.js
- pnpm-lock.yaml
Node has shipped `builtinModules` for some time now, so we no longer need a third party package to do this.
Once the `engines` constraint is bumped in the `package.json`, we can also move to using the built-in `isBuiltin` function (available since 16.x).
> chore(node-resolve): remove is-builtin-module

- packages/html/types/index.d.ts
Types incorrectly indicate that the `template()` function can sometimes be called without the `RollupHtmlTemplateOptions` argument. This yields to errors in IDE:
The workaround yields to poor DX:
There should not be any error when destructuring.
> fix(html): template function first arg is always provided

- packages/dynamic-import-vars/src/dynamic-import-to-glob.js
n/a
It looks like we can remove the unneeded `[]` for the regex as it contains only the `\w`. I discovered this while running `eslint-plugin-regexp`:
```
/Users/bjorn/Work/oss/vite/node_modules/.pnpm/@rollup+plugin-dynamic-import-vars@2.1.2_rollup@4.18.1/node_modules/@rollup/plugin-dynamic-import-vars/dist/cjs/index.js
117:47  error  Unexpected character class with one character class escape. Can remove brackets  regexp/no-useless-character-class
```
It's not a significant change and unlikely to affect perf, but should help with readability.
> fix(dynamic-import-vars): simplify regex

- packages/typescript/src/index.ts
- packages/typescript/src/options/validate.ts
- packages/typescript/test/test.js
Currently, when `output.file` is specified instead of `output.dir`, the filename for emitting declaration files with `this.emitFile` is resolved incorrectly. This means that given a `declarationDir` that is outside of the bundle output directory (which is `output.dir || dirname(output.file!)`), the declarations will still be generated inside the bundle, albeit in a location not actually matching `declarationDir` that does not respect the absolute file path generated by typescript. 
Whereas when using `output.dir`, `declarationDir` is actually validated and filenames for …
> fix(typescript)!: correctly resolve filenames of declaration files for `output.file`

- packages/typescript/README.md
- packages/typescript/src/moduleResolution.ts
- packages/typescript/src/options/tsconfig.ts
- packages/typescript/src/watchProgram.ts
- packages/typescript/test/test.js
- packages/typescript/types/index.d.ts
resolves #1667 
This allows creating custom transformers in the typescript plugin together ahead-of-time in a factory function. This allows for shorter rollup configs in certain cases and enables using similar factory-style transformers like the angular compiler API.
This also cleans up a few places minor internals in the typescript plugin (missing parameter descriptions, deprecated APIs, generic identifiers)
> feat(typescript): add transformers factory.

- packages/node-resolve/README.md
- packages/node-resolve/src/index.js
- packages/node-resolve/test/fixtures/prefer-builtin-local-and-builtin.js
- packages/node-resolve/test/prefer-builtins.js
- packages/node-resolve/types/index.d.ts
List any relevant issue numbers: resolves #1655
I think #1665 proposes a nice feature that gives `preferBuiltins` a more fine-grained control, so I'm trying to resolve this a little inactive issue.
This PR only makes `node-resolve` accept a function parameter to `preferBuiltins` to introduce as little as possible without changing the existing API.
#1665 also proposes that it should match the behavior of the `external` rollup configuration. But I think in most cases, we only need to mark some modules as non-builtins, e.g., deprecated modules like `punycode`. And this is somehow contrary to the behavior of the …
> feat(node-resolve): allow preferBuiltins to be a function

- packages/dynamic-import-vars/package.json
- packages/dynamic-import-vars/src/dynamic-import-to-glob.js
- packages/dynamic-import-vars/src/index.js
- pnpm-lock.yaml
https://npmgraph.js.org/?q=fast-glob - 17 dependencies
https://npmgraph.js.org/?q=tinyglobby - 2 dependencies
> chore(dynamic-import-vars): switch to tinyglobby for fewer dependencies

- packages/typescript/src/options/validate.ts
- packages/typescript/test/test.js
This change corrects a regression introduced by #1728, preventing dual bundle configs from writing output files to directories nested within the directory defined in the tsconfig's outDir property.
Example:
```js
export default {
input: 'src/index.ts', 
output: [
{
file: 'dist/cjs/index.cjs',
format: 'cjs',
},
{
file: 'dist/esm/index.mjs',
format: 'esm',
}
],
plugins: [
typescript({
tsconfig: 'tsconfig.json',
compilerOptions: {
outDir: 'dist'
}
})
],
};
```
Fixes #1773
> fix(typescript): allow for files to be nested in folders within outDir

- packages/dynamic-import-vars/package.json
- packages/dynamic-import-vars/src/dynamic-import-to-glob.js
- packages/dynamic-import-vars/src/index.js
- pnpm-lock.yaml
This reverts #1780 after the move to tinyglobby introduced a breaking change to normalized paths. See #1791 for more information.
> chore(dynamic-import-vars): revert 2.1.4 changes

- packages/pluginutils/package.json
- pnpm-lock.yaml
This PR upgrades picomatch used by pluginutils.
The only breaking change from 2.3.1 to 4.0.2 was the Node.js support range bump (from 8.6+ to 12+). pluginutils only support Node 14+, so this should be fine.
> fix(pluginutils): upgrade picomatch

- packages/commonjs/README.md
This recommendation also applies to IIFE format. When setting `output.exports: 'named'`, only the default value is exposed on the exported value.
refs #1639
refs https://github.com/vitejs/vite/issues/18574
> docs(commonjs): `output.exports` recommendation also applies to IIFE

- packages/replace/test/types.ts
- packages/replace/types/index.d.ts
Adds types for `objectGuards` which were missed in PR #1084.
> fix(replace): add missing types for `objectGuards` option

- packages/node-resolve/README.md
- packages/node-resolve/src/index.js
- packages/node-resolve/test/fixtures/dev-prod-conditions.js
- packages/node-resolve/test/fixtures/node_modules/dev-prod-conditions/dev.js
- packages/node-resolve/test/fixtures/node_modules/dev-prod-conditions/index.js
- packages/node-resolve/test/fixtures/node_modules/dev-prod-conditions/package.json
- packages/node-resolve/test/package-entry-points.js
closes https://github.com/rollup/plugins/issues/1819
Ensure that `development` or `production` is always set in `conditions`
> feat(node-resolve)!: set development or production condition

- packages/commonjs/src/resolve-require-sources.js
- packages/commonjs/test/test.js
In watch mode when the code imports CommonJS from ESM, depending on the setup, it can happen that the ES to Commonjs proxy module is re-evaluated. If that happens, its meta information is lost, leading to a weird crash.
I stumbled upon a case where in watch mode when changing a file, the CommonJS plugin would show a weird error. What happened is that a proxy module that was generated for a CommonJS from ESM import was being re-evaluated in its importer's `shouldTransformCachedModule` hook. Due to a small bug, the meta information of the proxy was lost, leading to a crash. This …
> fix(commonjs): fix crash with invalidated proxy modules

- packages/typescript/src/index.ts
- packages/typescript/test/fixtures/with-invalid-sources-inside-cwd/invalid.ts
- packages/typescript/test/fixtures/with-invalid-sources-inside-cwd/main.ts
- packages/typescript/test/fixtures/with-invalid-sources-inside-cwd/valid.ts
- packages/typescript/test/test.js
- packages/typescript/test/tslib.ts
- resolves #1652
This PR solves the issue described in #1652. It focuses on not creating a breaking changes by ensuring that no existing test was modified - except one that I'd like to discuss with the maintainers.
Basically, what this PR does is to remove the initial emit of **all** the files included in th working directory and instead emit files that are part of the dependency graph of the entry point.
> fix(typescript): fixes #1652 compile when source exists anywhere in the working directory

- packages/typescript/src/index.ts
- packages/typescript/test/fixtures/included-declarations/declarations.d.ts
- packages/typescript/test/fixtures/included-declarations/main.ts
- packages/typescript/test/fixtures/included-declarations/tsconfig.json
- packages/typescript/test/fixtures/with-invalid-sources-inside-cwd/invalid.ts
- packages/typescript/test/fixtures/with-invalid-sources-inside-cwd/main.ts
- packages/typescript/test/fixtures/with-invalid-sources-inside-cwd/valid.ts
- packages/typescript/test/test.js
- packages/typescript/test/tslib.ts
- resolves #1877
- resolves #1878
This reverts #1653 as many users were experiencing issues. If we want the feature, a new attempt should be made that tests for the issues described in #1877 and #1878
> fix(typescript): revert #1653

- packages/commonjs/src/transform-commonjs.js
Update the comment (based on latest logic by https://github.com/rollup/plugins/pull/1618) to avoid misleading others in the future.
> chore(repo): update comment to clarify top-level `this` rewrite

- packages/node-resolve/src/index.js
- packages/node-resolve/test/test.mjs
This improves the error message displayed to the user when the entry is `""` and the `node-resolve` plugin is used.
Before this change, the node-resolve plugin throws an error when the entry is `""` that is not helpful for the user to understand the problem ( `Cannot read properties of undefined (reading \'match\')`). Contrastingly, when not using the node-resolve plugin, rollup's error message is helpful: `Could not resolve entry module "".`
This pull request avoids the node-resolve error so that the clearer error message is displayed to the user.
> fix(node-resolve): error thrown with empty entry
